python core_room.py --area nympho --name "x420y-560z0" --short "North Transit" --long "Blue shaggy carpeting meets the dull grey cement as you come upon the best dome of all, the NymphoDome.  Inside there is plenty to do, but if you're leaving, we hope you will come back soon." --north 14 --anorth southeastmasstransit --south 7
python core_room.py --area nympho --name "x420y-630z0" --short "Nympho Lobby" --long "You are in the NymphoDome Lobby: a room pleasing to the eye for more reasons than one.  Complementing the room's pleasant decor, the occupants include both genders from all races.  The lobby is at the hub of access to the facilities in the Nympho dome: from the casino to the beach.\n\nA sign has been posted here." --item1 sign --item1desc "The Nympho Dome is currently undergoing renovations.  As such, certain areas may be made inaccessible without notice while construction teams are given access to the sites.  Please be patient." --north 7 --southwest 1 --southeast 1
python core_room.py --area nympho --name "x410y-640z0" --short "Entertainment District" --long "To the southwest stand two enormous doors, and although they are pretty dull and unentertaining from this side, the excited murmur escaping from the other side leads you to believe something better.  To your northeast lies the NymphoDome center." --northeast 1 --southwest 1
python core_room.py --area nympho --name "x400y-650z0" --short "Entertainment District Lobby" --long "From here you can go to any of the places in this quadrant, the casino, chapel, shops, and The Roxbury. To your south and east the casino begins, along with the other luxuries of the dome. There is also an exit to the northeast, leading back to the center of the dome." --southwest 1 --south 1 --northeast 1 --east 1
python core_room.py --area nympho --name "x410y-650z0" --short "Casino Ruins" --long "Remains of broken slot machines and busted blackjack tables are all over the place. It looks like this dome has seen better days. The atmosphere here still smells of thick smoke and dead zombie. To the west lies the exit and to all other directions the carnage continues." --west 1 --southwest 1 --south 1
python core_room.py --area nympho --name "x410y-660z0" --short "Casino Ruins" --long "Remains of broken slot machines and busted blackjack tables are all over the place. It looks like this dome has seen better days. The atmosphere here still smells of thick smoke and dead zombie. You might want to get out of here fast before stuff gets weird. The carnage continues in all directions and you can hear the faint laughing of a child in the background." --west 1 --south 1 --southwest 1 --north 1
python core_room.py --area nympho --name "x410y-670z0" --short "Casino Ruins" --long "Remains of broken slot machines and busted blackjack tables are all over the place. It looks like this dome has seen better days. The atmosphere here still smells of thick smoke and dead zombie.  Nobody is having fun here any more, except evil mog because he's a jerk. The carnage continues in all directions." --west 1 --southwest 1 --northwest 1 --north 1
python core_room.py --area nympho --name "x400y-660z0" --short "Casino Ruins" --long "Remains of broken slot machines and busted blackjack tables are all over the place. It looks like this dome has seen better days. The atmosphere here still smells of thick smoke and dead zombie. To the west is a small hallway leading to more shenanigans." --west 1 --southeast 1 --south 1 --northeast 1 --north 1 --east 1
python core_room.py --area nympho --name "x390y-660z0" --short "A Small Lobby" --long "This is a small lobby, with hallways and doors along all sides. A few benches, plants and small trees give the place an open atmosphere, and the soothing music that comes out of nowhere creeps you right out. To the west and south are a few shops to show someone how much you dislike them, The Roxbury is also this direction. To the north is the chapel, and to the east is the casino. The exit is to the northeast." --west 1 --south 1 --northeast 1 --north 1 --east 1
python core_room.py --area nympho --name "x380y-660z0" --short "Wide Hallway" --long "A few plants and a couple of benches line the sides of this hallway.  The lighting is low and creepy music plays from somewhere unknown, and the dark colors add to the creepy mood. North is the courthouse and to the south is a jewelers, and to the east and west hallway continues." --west 1 --southwest 1 --south 1 --northwest 1 --north 1 --east 1
python core_room.py --area nympho --name "x370y-660z0" --short "Gift Shoppe Ruins" --long "Broken and bloody teddybears are all over the floor. The counters are a mess and you can see decapitated teddybear heads everywhere. Obviously somebody hates teddy bears." --east 1
python core_room.py --area nympho --name "x370y-650z0" --short "A small lobby" --long "This is a small lobby, with hallways and doors along all sides. broken benches, plants and trees give this place the just destroyed by a zombie apocalpyse vibe. Creepy circus music seems to be coming from somewhere further adding to the creep factor. Blood smears are all over the walls. To the northwest is more carnage. The exit is to the southeast." --west 1 --southeast 1 --northwest 1 --north 1
python core_room.py --area nympho --name "x370y-640z0" --short "Killer Bunny Races" --long "A huge oval pit rests in the middle of the room, out lined by small, chalk written tracks. A human heart, mounted from a small rail on the side of the track, overhangs the small runways.  The destroyed rabbit cages are kept against the far southern wall, each used to contain a prized bunny but it looks like zombies have taken over." --west 1 --south 1 --southwest 1
python core_room.py --area nympho --name "x360y-640z0" --short "Game Gambling Center" --long "Welcome to the Gambling Center of the NymphoDome!  Here you used ot be able to place bets on games and contests and other oddities. The floors are all covered in blood and it appears as if the area hasn't been used in years." --southeast 1 --south 1 --east 1
python core_room.py --area nympho --name "x360y-650z0" --short "Mud Wrestling" --long "A huge pit in the middle of the room is filled to the top with mud.  The dirty, stained rope railing around the edge of the pit keeps the wrestlers from invading the small metal benches that seem to radiate from the pit." --northeast 1 --north 1 --east 1
python core_room.py --area nympho --name "x380y-650z0" --short "Court House" --long "A small, cramped office filled with stacks of papers and file cabinets awaits you.  The imitation oak desk has so many coffee stains on it it looks like it was actually made that way in the first place. An extremely depressing room to be in, all you want to do is get out." --south 1
python core_room.py --area nympho --name "x370y-670z0" --short "Candy Shoppe Ruins" --long "The nasty smell of brains, blood and guts fill this room. The walls and floors are covered with a mixture of blood, dirt, and grime. The display racks that once held candy are no more. You can hear creepy circus music coming from an unknown direction." --northeast 1
python core_room.py --area nympho --name "x380y-670z0" --short "Jewelry Shoppe Ruins" --long "Broken glass countertops sit on top of smashed shelving units. Oddly enough the jewlery is still in here but its all covered in blood and guts." --north 1 --east 1
python core_room.py --area nympho --name "x390y-670z0" --short "Wide Hallway" --long "A few plants and a couple of benches line the sides of this hallway.  Soft music plays from an indeterminate source.  The lighting is low and the gentle colors enhance the pleasant ambience.  Just to the west is the Jewelry Shoppe, to the east is the Casino, while the hallway continues north and south." --west 1 --south 1 --north 1 --east 1
python core_room.py --area nympho --name "x400y-670z0" --short "Casino Ruins" --long "Broken video poker machines are all over the place. Blood is stained into the carpet and the walls are covered in grime. The place smells like stale smoke and bad decisions. You hear zombies in the distance." --west 1 --south 1 --northeast 1 --north 1 --east 1
python core_room.py --area nympho --name "x400y-680z0" --short "Bingo Hall" --long "Long rows of tables and chairs stand in a huge room. Up front used to be a small stage but its long since been destroyed. You see some organs from an unknown creature splattered all over the floor." --west 1 --northeast 1 --north 1
python core_room.py --area nympho --name "x390y-680z0" --short "Wide Hallway" --long "A few plants and a couple of benches line the sides of this hallway.  The lighting is low and soft music plays from somewhere unknown, and the dark colors add to the creepy ambiance. North is a small hallway, to the east is bingo, to the west is a gift shoppe, and to the southeast is the Roxbury." --west 1 --southeast 1 --north 1 --east 1
python core_room.py --area nympho --name "x380y-680z0" --short "Flower Shoppe" --long "This looks like the remains of a flower shoppe. Broken vases are everywhere, the place smells of death and mold. Blood stains are all over the floor." --east 1
python core_room.py --area nympho --name "x400y-690z0" --short "The Roxbury" --scolor RED --lcolor BLUE --long "This is the outside of the newest and best night club ever to hit Core -- The Roxbury.  The outside has a few cage and pole dancers, bars, and lots of music.  In fact, it looks just like the inside should! Maybe you're on the list and you can go in to party." --northwest 1 --east 1 --mon1 groupie --mon2 groupie --mon3 groupie --mon4 groupie --mon5 loser --mon6 loser --mon7 loser --mon8 loser
python core_room.py --area nympho --name "x410y-690z0" --short "The Roxbury" --scolor RED --lcolor BLUE --long "This is the very front of the line for The Roxbury. Two bouncers stand ready to kick anyone out, and THE list is held in one of the bouncers hands. Hopefully your name is on it." --west 1 --north 1 --mon1 groupie --mon2 groupie --mon3 groupie --mon4 groupie --mon5 loser --mon6 loser --mon7 loser --mon8 loser --mon9 bouncer --mon10 bouncer
python core_room.py --area nympho --name "x410y-680z0" --short "The Roxbury" --scolor RED --lcolor BLUE --long "A huge overturned semi lays in the middle of the room. Around it lay jagged linings of streets, and across one wall, a long row of tires makes up the bar! The inside of the bar looks exactly the way it would on another planet's busy intersection!  Doesnt it just blow your mind?" --south 1 --mon1 groupie --mon2 groupie --mon3 bouncer --mon4 cagedancer --mon5 cagedancer --mon6 poledancer --mon7 poledancer --south 1
python core_room.py --area nympho --name "x430y-640z0" --short "Club Entrance" --long "This looks like a typical club entrance. Security guards are checking waiting potential patrons. It appears as if a long line is forming, apparently nobody is on the list." --northwest 1 --south 1 --mon1 clubbouncer --mon2 clubbouncer
python core_room.py --area nympho --name "x430y-650z0" --short "Dirty Nightclub" --long "The lights are down low and you can barely see anything. The walls are narrow and it feels cramped. Party goers are dancing everywhere and loud repetetive club music makes it impossible to hear." --south 1 --southeast 1 --north 1 --mon1 dancer --mon2 dancer
python core_room.py --area nympho --name "x430y-660z0" --short "Dirty Nightclub" --long "The only light in here appears to be ultra violet which makes all the stains on the walls and floors glow. Loud repetitive electronic mouse drowns out all other sounds and the mass of people make it so you can barely move." --south 1 --north 1 --mon1 dancer --mon2 dancer --mon3 dancer
python core_room.py --area nympho --name "x430y-670z0" --short "Nightclub" --long "The nightclub opens up a bit here and the music gets a little louder. Dancers can be seen all over the place." --north 1 --south 1 --mon1 dancer --mon2 dancer --mon3 child
python core_room.py --area nympho --name "x430y-680z0" --short "Nightclub" --long "The walls are all covered in neon uv reactive paint and the dance floor is filled with zombies and people. Once in a while a zombie bites a person but because its dark and everybody is drunk nobody notices. The music in this area has changed to a mid 90's eurodance variant known as CanaDance. This might just be Emjay - Flying to the Moon." --north 1 --south 1 --east 1 --mon1 dancer --mon2 dancer --mon3 dancer --mon4 zombie
python core_room.py --area nympho --name "x430y-690z0" --short "Nightclub" --long "The zombie infestation appears to be getting worse here. There are more zombies than there are dancers. The music is now a techno remix of total eclipse of the heart. The room is still dimly lit by bad uv lighting." --north 1 --east 1 --mon1 slowzombie --mon2 slowzombie --mon3 zombie --mon4 zombie --mon5 child
python core_room.py --area nympho --name "x440y-690z0" --short "Nightclub" --long "Walls are dark, floors are dark, lighting is terrible but the music is fantastic. Dancers and Zombies alike have come together to dance in pure harmony. The screams are somehow timed to the music which makes it even more entertaining. The dancers are way too out of it to even notice the zombies." --west 1 --northeast 1 --mon1 slowzombie --mon2 zombie --mon3 zombie
python core_room.py --area nympho --name "x450y-680z0" --short "Nightclub" --lcolor RED --long "The lights have shifted from UV to Red. Numerous creatures are in this area. You can't tell if its a goth convention or if the vampires are in town. The Humans don't seem to notice. The music is still extremely loud so that nobody can hear you scream." --southwest 1 --north 1 --east 1 --mon1 vampire --mon2 vampire --mon3 vampire --mon4 vampire --mon5 vampire --mon6 vampire --mon7 vampire
python core_room.py --area nympho --name "x440y-680z0" --short "Nightclub" --lcolor RED --long "The walls are all covered in blood, the only light is a dim red overhead light. Dancers are throbbing to the loud music." --west 1 --northeast 1 --mon1 dancer --mon2 dancer --mon3 dancer --mon4 dancer --mon5 vampire --mon6 child
python core_room.py --area nympho --name "x460y-680z0" --short "Nightclub" --long "Loud music is playing here. People seem to be dancing and enjoying it. Some zombies appear to be eating a humans flesh while the human is still alive and the human is doing nothing about it. There must be something in the air here." --west 1 --northeast 1 --mon1 zombie --mon2 zombie --mon3 zombie --mon4 zombie --mon5 slowzombie --mon6 slowzombie --mon7 child
python core_room.py --area nympho --name "x470y-670z0" --short "Nightclub" --long "This nightclub just seems to keep going forever. The masses of people, the loud music, the air that smells of recreational drugs all seem to meld into one giant throbbing mass." --southwest 1 --north 1 --mon1 dancer --mon2 dancer --mon3 dancer --mon4 dancer --mon5 dancer --mon6 dancer --mon7 dancer
python core_room.py --area nympho --name "x470y-660z0" --short "Nightclub" --long "The halls of the nightclub seem to open up a bit here, the music gets a little louder and the partiers seem to be partying harder. The walls here are clean as if they have just been wiped down." --northeast 1 --north 1 --south 1 --mon1 dancer --mon2 dancer --mon3 dancer --mon4 dancer --mon5 zombie --mon6 dancer --mon7 dancer --mon8 child
python core_room.py --area nympho --name "x470y-650z0" --short "Nightclub" --long "Partiers seem to be dancing the night away without a care in the world. Somehow they are all oblivious to the murderous clown in their midst. Even the zombies and vampires seem to have cleared out. There must be something about this clown." --south 1 --southwest 1 --northeast 1 --mon1 evilclown
python core_room.py --area nympho --name "x450y-670z0" --short "Nightclub" --lcolor RED --long "These damned vampires seem to be taking over the club. Terrible synthpop is playing in the background and everybody seems to be smoking cigarettes. The odd human is being devoured but nobody seems to mind. Nobody is drinking alcohol, everybody is drinking coffee in between blood frenzies. Its like a the goths from southpark became vampires and then somehow found their way here." --southwest 1 --northeast 1 --south 1 --mon1 vampire --mon2 vampire --mon3 vampire --mon4 vampire --mon5 vampire --mon6 vampire --mon7 vampire --mon8 vampire
python core_room.py --area nympho --name "x460y-660z0" --short "Nightclub" --scolor RED --long "Partiers are everywhere. The music is now back to the same old electronic dance music. Its not even good music like mid 90's pre drop trance, its not even house music. Its dubstep, it sounds like robots fornicating in here. Honestly the music is really bad. Since the music is like robots fornicating it appears as if the Humans in the club are doing the same. No vampires, goths, clowns, or even zombies to be found." --southwest 1 --northeast 1 --mon1 dancer --mon2 dancer --mon3 dancer --mon4 dancer --mon5 dancer --mon6 dancer --mon7 dancer --mon8 dancer --mon6 child
python core_room.py --area nympho --name "x480y-650z0" --short "Nightclub" --long "The crowds seem to be thinning out, all you can see is zombies and vampires but no humans. The music sounds like robots fornicating." --southwest 1 --north 1 --mon1 zombie --mon2 slowzombie --mon3 vampire --mon4 vampire --mon6 child
python core_room.py --area nympho --name "x480y-640z0" --short "Nightclub" --long "Shenanigans abound there seems to be no zombies, or vampires. You can't quite tell if the clown is gone though. The music appears to be a techno circus remix and its definitely creeping you out." --south 1 --west 1 --southwest 1 --mon1 clown --mon2 dancer --mon3 dancer --mon4 dancer --mon5 dancer --mon6 dancer
python core_room.py --area nympho --name "x470y-640z0" --short "Nightclub" --long "The music is loud and the partiers seem to be partying hard. The music is loud and likely some sort of Top 40 trash, you can't quite tell who's playing but it sounds cookie cutter, like Nickleback but even worse." --east 1 --west 1 --mon1 dancer --mon2 dancer --mon3 vampire --mon4 zombie
python core_room.py --area nympho --name "x460y-640z0" --short "Nightclub" --long "Partiers can be seen everywhere, the lights seem to be dim and the uv is really showing that this place needs a scrub down. The music is oh so re·pet·i·tive." --west 1 --east 1 --mon1 dancer --mon2 dancer --mon3 dancer
python core_room.py --area nympho --name "x450y-640z0" --short "Nightclub" --long "Lets be honest evilmog is running out of material, first clowns then zombies, then vampires and goths. What's it going to be next? Evil Cats? Oh Wait they are doing a movie based on cats, and its terrible. No you do not see dancing cats in this nightclub, not happening on my watch, thats how you get furries, if you wanted furries you would be in another dome." --east 1 --west 1  --mon1 dancer --mon2 zombie --mon3 slowzombie --mon4 vampire --mon5 child --mon6 child
python core_room.py --area nympho --name "x440y-640z0" --short "Nightclub" --long "Yeah I'm out of material, just imagine a nightclub, imagine your favorite music, now imagine the exact opposite of that. This place makes your skin crawl. You know that clown is out to get you.  Oh and the music is bad, like terrible re·pet·i·tive nightclub music." --east 1 --southeast 1 --mon1 dancer --mon2 dancer --mon3 dancer --mon4 dancer --mon5 dancer --mon6 dancer --mon7 dancer
python core_room.py --area nympho --name "x450y-650z0" --short "VIP Entrance" --long "Security guards appear to be stopping those not on the list. There is a velvet rope blocking off access to the VIP area." --northwest 1 --south 1 --mon1 vipbouncer --mon2 vipbouncer
python core_room.py --area nympho --name "x440y-660z0" --short "VIP Entrance" --long "Security guards appear to be stopping those not on the list. There is a velvet rope blocking off access to the VIP area." --northwest 1 --east 1 --mon1 vipbouncer --mon2 vipbouncer
python core_room.py --area nympho --name "x450y-660z0" --short "Center Stage" --long "There is an array of dancers in cages and on poles to entertain the VIP's. The music is softer here so you can have a proper conversation. The lighting is soft and subdued as well." --southwest 1 --northeast 1 --southeast 1 --mon1 poledancer --mon2 cagedancer --mon3 poledancer --mon4 cagedancer --mon5 poledancer --mon6 cagedancer --mon7 poledancer --mon8 cagedancer --north 1 --west 1
