python core_npc.py --name "jackback" --label "Jack Back" --id1 jack --id2 back --id3 trader --short "Jack Back, Trader" --long "Jack has a look about him that makes you think he's seen a lot around here.  He wears a nice suit.  Leaning against the wall in the corner, his legs are crossed as he smokes a cigar.  A fedora is tilted to cover most of his face." --level 14 --gender male
python core_npc.py --name "clara" --label "Receptionist Clara" --id1 receptionist --id2 clara --short "Receptionist Clara" --long "Clara has been working as a receptionist at Milkitrade since 51.  She is not much to look at, but her tail does peak your interest.  She is wearing a light blue business suit." --level 14 --gender female
python core_npc.py --name "wellin" --label "President Wellin" --id1 president --id2 wellin --short "President Wellin" --long "President Wellin does not live up to his title or name very well.  He is far from presidential or well.  He looks run down.  His suit is dirty, and his tie is undone.  It seems that his company's lack of success has taken its toll on his appearance." --level 14 --gender male
python core_npc.py --name "gana" --label "Trade Manager Gana" --id1 gana --id2 manager --id3 trade --short "Trade Manager Gana" --long "Gana Lou is the trade manager of Milkitrade.  She has blond hair and bright blue eyes.  She wears a light blue beret on top of her head, accenting her similarly colored dress." --gender female --level 14
python core_npc.py --name "jackie" --label "Receptionist Jackie" --id1 jackie --id2 receiptionist --short "Receptionist Jackie" --long "Jackie has long curly black hair and a remarkably clear, pale face.  She greets you with a beautiful smile and a casual nod.  Although she is new at L.T. Smith, you can tell that she is a quick learner." --level 14 --gender female
python core_npc.py --name "colleen" --label "Trade Manager Colleen" --id1 colleen --id2 trade --id3 manager --short "Trade Manager Colleen" --long "Colleen Noah is the trade manager of LT Smith.  Colleen has been the trade manager here since the company's beginnings in 2646.  She can be most accurately be described as average.  Nothing about her strikes you as being particuarly bad, good, or interesting." --level 14 --gender female
python core_npc.py --name "smith" --label "President Smith" --id1 smith --id2 president --short "President Smith" --long "President Smith immediately strikes you as a powerful individual. Everything about him radiates it: his clothes, countenance, and posture. He wears an expensive looking black suit with a red tie.  The success of his company must be treating him very well." --level 14 --gender male
python core_npc.py --name "neelo" --label "Security Officer Neelo" --id1 neelo --id2 security --id3 officer --short "Security Officer Neelo" --long "Neelo is Director FirstFuzz Greptags personal security officer.  As head security officer of CFTC, Neelo is responsible for maintaining a responsible business atmosphere above the stock exchange. He wears a pinstripe suit with a fancy hat." --level 14 --gender male
python core_npc.py --name "sarah" --label "Receptionist Sarah" --id1 sarah --id2 receptionist --gender female  --level 13 --short "Receptionist Sarah" --long "Sarah has seems to have grown rather large over the years.  She tends to be reading a magazine or eating something instead of helping anyone, a testament to the lack of work coming in to Galactic Securities."
python core_npc.py --name "tweeter" --label "Vice President Tweeter" --id1 tweeter --id2 vp --short "Vice President Tweeter" --long "Vice President Tweeter has been assigned to the Core Branch of Galactic Securities.  Although GSec doesn't do a lot of business on Core, Tweeter doesn't see that as a bad thing.  The higher-ups in the company don't expect anything from this little outpost, so Tweeter gets to lounge around." --level 14 --gender male
python core_npc.py --name "blupeah" --label "Blu Peah" --id1 blu --id2 blupeah --id3 peah --short "Assistant System Administrator Blu Peah" --gender male --level 14 --long "Always enjoying the shadows, Blu Peah deals with all the lower level system administration tasks required by the Center. Wearing casual clothing is his MO.  However, his fashion-sense is somewhat lacking, as displayed by his pale green shirt and bright blue pants." 
python core_npc.py --name "collette" --label "Receptionist Collette" --id1 collette --id2 receptionist --short "Receptionist Collette" --long "Collette is very ugly.  Diana must not want any competition for the title of hottest chick on Core. Frizzled hair and acne plague this poor woman that probably grew up in the mines on a distant planet." --level 14 --gender female
python core_npc.py --name "diana" --id1 branch --id2 manager --id3 diana --label "Branch Manager Diana" --long "Diana is extremely attractive. She has long legs that lead up to her short, purple business skirt. She has long curly brown hair framing her perfect face. As branch manager on a planet unimportant to Mars Financial's future, Diana does not have a lot of work to do here. his leaves her time open for other pursuits." --level 16 --gender female --short "Branch Manager Diana"

