#!/usr/bin/env bash
python core_npc.py --name "mamba" --label "Black Mamba" --id1 mamba --id2 black --id3 blackmamba --short "Black Mamba" --long "This is a long and evil looking snake, black with green diamonds on its back. It looks at you through dark green eyes and in its open mouth you can see poison-dripping fangs. It slithers around but never stops staring at you." --level 3 --gender neuter
python core_npc.py --name "monkey" --label "Cuddly Monkey" --id1 monkey --id2 cuddly --id3 cuddlymonkey --short "Cuddly Monkey" --long "This little monkey is extremely cute and fluffy, with soft brown fur and a lovely little cute face. It looks up at you with an expression of trusting innocence and snikkers softly. All in all, it looks like it could just use a cuddle." --level 2 --gender male
python core_npc.py --name "doe" --label "Red Doe" --id1 red --id2 doe --id3 reddoe --short "Red Doe" --long "This is a timid forest animal, and it looks around it nervously, ready to run away if it feels threatened. It is a soft eyed red deer, female probably, since it has no large antlers. It looks very weak, and defenceless, and you wish you could just stroke it's head and whisper to it that everything will be all right, but unfortunately, it will not". --gender female --level 2
python core_npc.py --name "boar" --label "Wild Boar" --id1 boar --id2 wild --id3 wildboar --short "Wild Boar" --long "This is a fat and very ugly wild boar. It has tusks that look fairly dangerous, but must move very slowly on its short stubby legs. It is so immensely fat that it is in fact shaped somewhat like a barrel, and it's belly almost scrapes the ground as it walks. It is warty and deserves to die for smelling so disgustingly horrible!" --gender male --level 4
python core_npc.py --name "baboon" --label "Insane Baboon" --id1 baboon --id2 insane --id3 insanebaboon --short "Insane Baboon" --long "This is a gibbering, crazy, lunatic Baboon. It looks mad enough to be a Pink Floyd listener, hell it even looks mad enough to understand the WALL! Hmm, mebbe it might not be such a great idea to attack such a barmy creature!, Then again, mebbe someone ought to put it out of its misery!" --level 3 --gender male
python core_npc.py --name "python" --label "Fierce Python" --id1 fierce --id2 python --id3 fiercepython --short "Fierce Python" --long "This is a very long and heavy built python, which is wrapped around a tree, it's head waving in the air before you. It's slit pupiled eyes look at you with a cold stare and its forked tongue flits in and out of its mouth in a constant rapid flicker." --level 3 --gender maleo
python core_npc.py --name "gorilla" --label "Big Moma Gorilla" --id1 gorilla --id2 moma --id3 big --short "Big Moma Gorilla" --long "Big Moma must weigh more than a metric tonne, she is very very big, and very very angry. She looks like she could take your weapon and shove it right up emm, yeah. Do NOT attack Big Moma unless you consider yourself as hard as nails.! Walk very carefully, so you don't disturb her, and just don't get her any more pissed off than absolutely necessary!" --level 4 --gender female
python core_npc.py --name "panther" --label "Black Panther" --id1 panther --id2 black --id3 blackpanther --short "Black Panther" --long "This is a sleek black panther that pads around the jungle in a dark and threatening manner. It is completely black all over, except for its eyes, which are blazing yellow and glow with an evil glint. It looks hungry and it also looks like it could eat you without too much trouble, so maybe you better move along." --level 3 --gender female
python core_npc.py --name "zaryem" --label "Zaryem" --id1 zaryem --short "Zaryem, Maintenance officer" --long "Zaryem smells strongly of disinfectant, a result of having have to wash up his own office after the maintenance droids suddenly left for their regularly scheduled maintenance checks. The maintenance officer is not in a very good mood at the moment, and it is highly advisable not to get on his nerves anymore than one should." --level 8 --gender male
python core_npc.py --name "vlarapp" --label "Vlarapp" --id1 vlarapp --short "Vlarapp, East dome manager" --long "Clothed in a blue uniform, this overweight abernon is the dome manager of the East dome. Vlarapp, like all abernons, bears a deeply ingrained hatred for all the other races. But his abilities in management are beyond compare, and so the Company made him manager of the dome. Although he might seem a little grouchy at all times, Vlarapp can actually be a pretty decent abernon if you catch him at the right time. However, he is a tidiness freak, so try not to approach him unless you are currently being immaculately tidy." --level 4 --gender male
python core_npc.py --name "mila" --label "Mila" --id1 mila --short "Mila, dome managers secretary" --long "A human female from Earth who hails from the country once known to all as Russia, Mila is an attractive female in her mid-twenties who has been involved with the Company for all her life. Her parents were Company employees, and she was brought up in a Company environment. Her decision to work for the Company in Core is more of an issue of destiny. She would not have fit in anywhere else anyway." --level 3 --gender female
python core_npc.py --name "planner" --label "Planner" --id1 planner --short "Planner" --long "Eyes creased in concentration, the planner is a specially-elected individual from the various East dome departments to help plan out general dome policy outlines and other such matters. He is always deep in thought, mentally going through the plans for the East dome over and over again in his mind. Do not disturb his mental train of thought." --level 8 --gender male
python core_npc.py --name "roger" --label "Roger Delgado" --id1 roger --id2 delgado --id3 rogerdelgado --short "Roger Delgado, East dome Public Relations Officer" --long "You are looking at Roger Delgado, the public relations officer of the East dome. He is a handsome man of perhaps thirty. Dressed in an exclusive-looking suit, you can see that Roger does have a brilliant sense of dressing. A whiff of expensive cologne drifts pass you. You can see that Roger is a true gentleman." --level 5 --gender male
python core_npc.py --name "maintainer" --label "Droid Maintainer" --id1 droid --id2 maintainer --id3 droidmaintainer --short "Droid Maintainer" --long "The droid maintainer may be humanoid in shape, but thats where any other similarity to humans end. Standing over 6 feet tall and made fully out of a strong silicon-steel alloy, the maintainer is a walking hulk of metal death. The strength and endurance of the maintainer allows it to work for extended hours maintaining other droids." --level 4 --gender male
python core_npc.py --name "powerdrone" --label "Power Drone" --id1 power --id2 drone --id3 powerdrone --short "Power Drone" --long "Spherically shaped and painted grey in color, the power drones main purpose is to connect the power cables to the droids during the recharging process. Due to the labour-orientated nature of their work, the power drones are stronger than most of the usual droids." --level 5 --gender neuter
python core_npc.py --name "alexis" --label "Alexis" --id1 alexis --id2 receptionist --short "Alexis, East dome receptionist" --long "Dressed in a pretty white dress, Alexis is the receptionist of the East dome. She handles most of the incoming inhabitants to the dome, as well as greets the current inhabitants as they return home from their work. She is a sweet little thing, and it's no wonder that she was selected to be a receptionist here." --level 4 --gender female
python core_npc.py --name "eastclerk" --label "clerk" --id1 clerk --short "clerk" --long "This is a clerk who is working in the East dome. Rest is of no repose here, for work is neverending, and the assignments just pile up without any reprieve. You wonder how long more this clerk will live before a high blood pressure brings about death. " --level 3 --gender neuter
python core_npc.py --name "eastfilingclerk" --label "filing clerk" --id1 clerk --id2 filing --id3 filingclerk --id4 "filing clerk" --short "filing clerk" --long "This bored-looking teenager is a filing clerk. Her purpose is to file away unneeded files and retrieve required ones. Not a permanent worker, she is just passing time here and is therefore not putting full effort into what she is doing." --gender female --level 4
python core_npc.py --name "lyndia" --label "Lyndia" --id1 lyndia --id2 head --id3 clerical --id4 clericalhead --id5 "clerical head" --short "Lyndia, Clerical Head" --long "Lyndia is a woman in her early thirties. She has worked hard to get to where she's at, and although her pay isn't all that good, she's' more than contented with what she has got. These days, she works hard for the Company, giving everything her best. This has resulted in her getting good reviews from her superiors. The future looks pretty bright for this clerical head in the Company." --level 3 --gender female
python core_npc.py --name "eastformatter" --label "formatter" --id1 formatter --short "formatter" --long "This gorbu formatter looks sleepy, a result of having to guide the formatting of the documents via the computer for hours without end. You can see that she would rather be somewhere else, like maybe soaking in a nice cool pool of water underneath a hot sun. Unfortunately, there is still much work to be done before that can become a reality. " --level 4 --gender female
python core_npc.py --name "eastauthorizer" --label "clerical authorizer" --id1 clerical --id2 authorizer --id3 clericalauthorizer --short "clerical authorizer" --long "Looking self-important and disgustingly pleased with himself, the clerical authorizer is a pompous man who thinks that his job is the greatest one on Core. Although he doesn't carry much importance at all, the authorizer acts as if he is bigger than the dome manager himself, and constantly gripes about how he should be promoted to some better dome which deserves his services more. " --level 3 --gender male
python core_npc.py --name "outfitterrobot" --label "outfitter robot" --id1 robot --id2 outfitter --id3 outfitterrobot --short "outfitter robot" --long "This four-legged robot is yellow in color. It is rather huge, and a highly-developed sense of dexterity has been programmed into it to allow minute manipulations of droid parts in the outfitting process. Although it is invariably large, the outfitter has been given very accurate sensors to avoid unwarranted accidents as it moves around. " --level 6 --gender neuter
python core_npc.py --name "eastmaintenancedroid" --label "idle maintenance droid" --id1 idle --id2 maintenance --id3 droid --id4 maintenancedroid --id5 idledroid --short "idle maintenance droid" --long "This squat pepperpot-shaped droid is currently in its dock as it undergoes basic diagnostics checks and maintenance runs to assure that it is functioning in top and optimum condition at all times. Do not disturb its rest." --gender neuter --level 4
python core_npc.py --name "ursula" --label "Ursula" --id1 ursula --id2 registrar --short "Ursula, secretary of the East dome registrar" --long "Ursula has got to be the most solemn nympho you have ever seen. Clothed in a sexy lily-colored blouse which more than exhibits her curvaceous body, Ursula sits in a rigidly straight pose as she goes about her work. Her eyes are fiercely fixed on the task at hand, her mouth a firm thin line. Definitely not a nympho to take home to bed with you." --gender female --level 6
python core_npc.py --name "vonnewman" --label "Von Newman" --id1 von --id2 newman --id3 registrar --id4 vonnewman --short "Von Newman, East dome registrar" --long "An strange piercing aura surrounds the East dome registrar. You get the feeling that there is something very weird about him, but can't seem to figure out what. Perhaps it's the feeling that you're both not alone in this room. Or maybe it's the fact that you feel his eyes constantly on you although he's not looking at you. Whatever the case, this man gives you the creeps. " --level 2 --gender male
