#!/usr/bin/env bash
python core_npc.py --name "mamba" --short "Black Mamba" --long "This is a long and evil looking snake, black with green diamonds on its back. It looks at you through dark green eyes and in its open mouth you can see poison-dripping fangs. It slithers around but never stops staring at you." --level 5 --gender neuter
python core_npc.py --name "monkey" --short "Cuddly Monkey" --long "This little monkey is extremely cute and fluffy, with soft brown fur and a lovely little cute face. It looks up at you with an expression of trusting innocence and snikkers softly. All in all, it looks like it could just use a cuddle." --level 4 --gender male
python core_npc.py --name "doe" --short "Red Doe" --long "This is a timid forest animal, and it looks around it nervously, ready to run away if it feels threatened. It is a soft eyed red deer, female probably, since it has no large antlers. It looks very weak, and defenceless, and you wish you could just stroke it's head and whisper to it that everything will be all right, but unfortunately, it will not". --gender female --level 2
python core_npc.py --name "boar" --short "Wild Boar" --long "This is a fat and very ugly wild boar. It has tusks that look fairly dangerous, but must move very slowly on its short stubby legs. It is so immensely fat that it is in fact shaped somewhat like a barrel, and it's belly almost scrapes the ground as it walks. It is warty and deserves to die for smelling so disgustingly horrible!" --gender male --level 5
python core_npc.py --name "baboon" --short "Insane Baboon" --long "This is a gibbering, crazy, lunatic Baboon. It looks mad enough to be a Pink Floyd listener, hell it even looks mad enough to understand the WALL! Hmm, mebbe it might not be such a great idea to attack such a barmy creature!, Then again, mebbe someone ought to put it out of its misery!" --level 3 --gender male
python core_npc.py --name "python" --short "Fierce Python" --long "This is a very long and heavy built python, which is wrapped around a tree, it's head waving in the air before you. It's slit pupiled eyes look at you with a cold stare and its forked tongue flits in and out of its mouth in a constant rapid flicker." --level 3 --gender maleo
python core_npc.py --name "gorilla" --short "Big Moma Gorilla" --long "Big Moma must weigh more than a metric tonne, she is very very big, and very very angry. She looks like she could take your weapon and shove it right up emm, yeah. Do NOT attack Big Moma unless you consider yourself as hard as nails.! Walk very carefully, so you don't disturb her, and just don't get her any more pissed off than absolutely necessary!" --level 6 --gender female
python core_npc.py --name "panther" --short "Black Panther" --long "This is a sleek black panther that pads around the jungle in a dark and threatening manner. It is completely black all over, except for its eyes, which are blazing yellow and glow with an evil glint. It looks hungry and it also looks like it could eat you without too much trouble, so maybe you better move along." --level 5 --gender female
python core_npc.py --name "zaryem" --short "Zaryem, Maintenance officer" --long "Zaryem smells strongly of disinfectant, a result of having have to wash up his own office after the maintenance droids suddenly left for their regularly scheduled maintenance checks. The maintenance officer is not in a very good mood at the moment, and it is highly advisable not to get on his nerves anymore than one should." --level 12 --gender male
python core_npc.py --name "vlarapp" --short "Vlarapp, East dome manager" --long "Clothed in a blue uniform, this overweight abernon is the dome manager of the East dome. Vlarapp, like all abernons, bears a deeply ingrained hatred for all the other races. But his abilities in management are beyond compare, and so the Company made him manager of the dome. Although he might seem a little grouchy at all times, Vlarapp can actually be a pretty decent abernon if you catch him at the right time. However, he is a tidiness freak, so try not to approach him unless you are currently being immaculately tidy." --level 12 --gender male
python core_npc.py --name "mila" --short "Mila, dome managers secretary" --long "A human female from Earth who hails from the country once known to all as Russia, Mila is an attractive female in her mid-twenties who has been involved with the Company for all her life. Her parents were Company employees, and she was brought up in a Company environment. Her decision to work for the Company in Core is more of an issue of destiny. She would not have fit in anywhere else anyway." --level 11 --gender female
python core_npc.py --name "planner" --short "Planner" --long "Eyes creased in concentration, the planner is a specially-elected individual from the various East dome departments to help plan out general dome policy outlines and other such matters. He is always deep in thought, mentally going through the plans for the East dome over and over again in his mind. Do not disturb his mental train of thought." --level 10 --gender male
python core_npc.py --name "roger" --short "Roger Delgado, East dome Public Relations Officer" --long "You are looking at Roger Delgado, the public relations officer of the East dome. He is a handsome man of perhaps thirty. Dressed in an exclusive-looking suit, you can see that Roger does have a brilliant sense of dressing. A whiff of expensive cologne drifts pass you. You can see that Roger is a true gentleman." --level 10 --gender male
python core_npc.py --name "maintainer" --short "Droid Maintainer" --long "The droid maintainer may be humanoid in shape, but thats where any other similarity to humans end. Standing over 6 feet tall and made fully out of a strong silicon-steel alloy, the maintainer is a walking hulk of metal death. The strength and endurance of the maintainer allows it to work for extended hours maintaining other droids." --level 11
python core_npc.py --name "powerdrone" --short "power drone" --long "Spherically shaped and painted grey in color, the power drones main purpose is to connect the power cables to the droids during the recharging process. Due to the labour-orientated nature of their work, the power drones are stronger than most of the usual droids." --level 11 --gender neuter
