python core_room.py --area westmine --name "x-590y0z0" --short "West Mine - Eastern Transit Station" --long "This is it...  the crown jewel in The Company's vast mining empire.  Of all the mining facilities in all of their colonies, none can compare to the riches found within the West Mine on the Hermes-571G colony!  Here can be found the rare spaceship fueling mineral corezite -- a mineral believed only to exist in theory and impossible to reproduce in a laboratory.  Yet by some freak of creation it has ended up here!  Due to the high financial risk posed by inexperienced miners causing accidents here, only the most skilled miners may extract corezite from the West Mine." --east 17 --aeast westmasstransit --west 4 --southwest 1 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-600y-10z0" --short "Guard Barracks." --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --northeast 1 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-630y0z0" --short "West Mine - Central Transit Station" --long "So years ago the company sold off all its mines, it replaced them with digital currency mines. All the corezite that was year was mined out years ago to make the fusion reactors that make up this digital mine. Chairs are all over the place lined up against terminals.\n\nYou should try to '%^MAGENTA%^crypto%^RESET%^' here." --east 4 --west 4 --south 4 --north 4
python core_room.py --area westmine --name "x-630y40z0" --short "West Mine - Northern Transit Station" --long "Despite the constant cleaning efforts, the maintenance crews haven't been able to completely remove the mine soot that has been ground into the floor.  This can be none other than one of The Company's mine domes." --southeast 1 --south 4 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-620y30z0" --short "Guard Barracks" --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --northwest 1 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-630y-40z0" --short "West Mine - Southern Transit Station" --long "Despite the constant cleaning efforts, the maintenance crews haven't been able to completely remove the mine soot that has been ground into the floor.  This can be none other than one of The Company's mine domes." --northwest 1 --north 4 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-640y-30z0" --short "Guard Barracks" --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --southeast 1 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-670y0z0" --short "West Mine - Western Transit Station" --long "Despite the constant cleaning efforts, the maintenance crews haven't been able to completely remove the mine soot that has been ground into the floor.  This can be none other than one of The Company's mine domes." --northeast 1 --east 4 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-660y10z0" --short "Guard Barracks" --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --southwest 1 --mon1 guard --mon2 guard
python core_room.py --area southmine --name "x0y-590z0" --short "South Mine - Northern Transit Station" --long "This is the northern tip of the South Mine, famous for producing the more expensive metals demanded by the merchant shops." --south 4 --north 17 --anorth "southmasstransit" --mon1 guard --mon2 guard --southeast 1
python core_room.py --area southmine --name "x10y-600z0" --short "Guard Barracks" --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --northwest 1 --mon1 guard --mon2 guard
python core_room.py --area southmine --name "x0y-630z0" --short "South Mine - Central Transit Station" --long "This is the center of the prestigous South Mine.  One of the richest mines in existence in any of The Company's mining colonies, this mine specializes in the highly sought-after material mithril.  Any miner who frequents this mine will soon become fast friends with many a shopowner!" --west 4 --north 4 --south 4 --east 4
python core_room.py --area southmine --name "x-40y-630z0" --short "South Mine - Western Transit Station" --long "This is the south mine west transit tube. Its not hooked up to anything. Mostly because I'm lazy, thats it I'm lazy and there's nothing you can do about it." --northeast 1 --east 4 --mon1 guard --mon2 guard
python core_room.py --area southmine --name "x-30y-620z0" --short "Guard Barracks" --long "Lets be honest, I'm using cookie cutter descriptions, they are really boring and you are tired of reading them. Supposedly some off duty guards hang out here, or whatever." --southwest 1 --mon1 guard --mon2 guard
python core_room.py --area southmine --name "x40y-630z0" --short "South Mine - Eastern Transit Station" --long "This area isn't setup either, I'm too lazy to to do it, the mine code will likely be half baked. In theory this is supposed to be some sort of mass transit station hooked up to nothing, going nowhere, sorry.  I'm not really sorry though, you are probably reading this looking for deeper meaning because you really want a derbycon ticket. Good Luck." --west 4 --southwest 1 --mon1 guard --mon2 guard
python core_room.py --area southmine --name "x30y-640z0" --short "Guard Barracks" --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --northeast 1 --mon1 guard --mon2 guard
python core_room.py --area southmine --name "x0y-670z0" --short "South Mine - Southern Transit Station" --long "Ok look you are literally out in the sticks. There is supposed to be a mass transit node out here or whatever but its not hooked up to anything. Good luck searching for that ticket." --north 4 --northwest 1 --mon1 guard --mon2 guard
python core_room.py --area southmine --name "x-10y-660z0" --short "Guard Barracks" --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --southeast 1 --mon1 guard --mon2 guard

