python core_room.py --name "x110y0z0" --short "East Housing Dome - West Mass-Transit" --long "You have just entered housing dome #2 through an airlock. This dome is a bit smaller than the first but not as low-quality.  You see a conveyor belt ahead of you with its riders heading towards the central area." --west 1 --east 10
python core_room.py --name "x210y0z0" --short "East Housing Dome: Center" --long  "The conveyor belt has brought you to the central area. Habitants are moving boxes of equipment into the housing building in front of you.  There are benches for people to sit on while they can watch the children frolic in the nearby playground.  There seem to be some important looking edifices to the southeast.\n\n You can visit the Atrium by going to the southwest." --west 10 --south 10 --north 10 --east 10 --southeast 1 --southwest 1 --up 1
python core_room.py --name "x200y-10z0" --short "Atrium Entrance" --long "Lush exotic-looking plants grow abundantly all over this place. This is the entrance of an atrium located in the East Housing dome. The floor around you is paved with cement, while fresh soil cover the wide areas around the cement walkway. This atriums main purpose is to keep the natural air balance of the dome stable while at the same time providing sanctuary for the animals from Earth which have been transported to the colony.\n\nA metal archway to the northeast, lined with vines, lead to the the center mass-transit station of the East Housing dome. The cement walkway continues onward to the southwest." --northeast 1 --southwest 1 --obj1 mamba
python core_room.py --name "x190y-20z0" --short "Atrium Walkway" --long "On both sides of the cement walkway are thick heavy foliage made out of strange plants which you hardly recognize. The dense plants make this walkway dark, obscuring the soft lightpanels above. Suspended just below the ceiling is a crazy network of iron water sprinklers which run off haphazardly everywhere.\n\nThe atrium entrance lies to your northeast. The walkway also extends to the southeast and southwest." --southwest 1 --southeast 1 --northeast 1 --obj1 doe
python core_room.py --name "x200y-30z0" --short "Atrium Walkway" --long "The walkway is sandwiched between very dense greenery, all of which is composed of plants both exotic and strange in nature. Illumination from the lightpanels above shed shadows as the light is blocked by the numerous leaves and scrubs. This results in the walkway being very dim, with just enough light to see where you're going.\n\nTo your north is the filtering area. A clearing can be reached by heading northwest." --north 1 --northwest 1 --obj1 monkey
python core_room.py --name "x200y-20z0" --short "Filtering Area" --long "The cement path comes to an end here. Plants and small trees grow abundantly here, but the dense foliage cannot hide the large bulky air filters which have been fastened securely to the eastern wall. Because of the filters, the leaves and some of the softer-vined plants in this area are in a perpetual state of rustling.\n\nYou can leave by heading south." --south 1 --obj1 boar
python core_room.py --name "x180y-30z0" --short "Atrium Walkway" --long "This cement path is the only thing which keeps the plants from growing over the many various passages in the atrium. The air is wet with moisture, courtesy of the water sprinklers suspended just below the ceiling. Lightpanels overhead illuminate the passage dimly, partially caused by the obstructing leafage. \n\nClearings are located to both your east and west. The atrium walkway continues northeast." --west 1 --northeast 1 --east 1 --obj1 monkey
python core_room.py --name "x190y-30z0" --short "A clearing" --long "You have reached a clearing in the atrium. Here, the ceiling is over twelve feet high, and bright solar-panels radiate artificial solar energy down upon you. There is little sign of the exotic plants which so populate the atrium in this clearing.\n\nThe walkway extends to your west and southwest. A panel set into the high metal wall takes you into a passage southeast from here." --west 1 --southwest 1 --southeast 1 --obj1 baboon
python core_room.py --name "x200y-40z0" --short "Service Passage" --long "This corridor is made out of brick-layered walls and black-tiled floor. In the ceiling, a row of small turbines from north to south spins lazily, while red lights beneath them illuminate the passage. \n\nA panel in the wall leads out northwest, while the atrium service room lies to the south." --south 1 --northwest 1
python core_room.py --name "x200y-50z0" --short "Atrium service room" --long "This is a rather small room, with steel walls and a large turbine spinning away above a heavy iron grate in the ceiling. To the south of the room is a semi-circular array of consoles, each indicating the status of various environmental controls in the atrium itself. The soft whirrings and the occasional clicking sound in the background hints of the self-automated nature of this service room.\n\nThe door to your north takes you out to a service passage." --north 1
python core_room.py --name "x180y-40z0" --short "Atrium Walkway" --long "Lightpanels in the ceiling mutely illuminate this cement walkway. On both sides of the path are plants, all of which are unfamiliar to you. Above you, hanging below the lightpanels, is a crazy network of water sprinklers. The foliage partially obstructs the light from above, causing the walkway to appear dim.\n\nYou can feel a slight draft heading southeast. The plants seem to get thicker to your east and west, while a clearing lies to your northeast." --west 1 --southeast 1 --northeast 1 --east 1 --obj1 python
python core_room.py --name "x190y-50z0" --short "Inflow area" --long "Among the heavy foliage here are pairs of iron pipes with metal gratings on them fixed to the eastern wall. The air around you is being sucked into the pipes, which hum constantly with the effort. A bunch of loose leaves are collected untidily beneath the pipes, blocked by the gratings from entering the pipes.\n\nThe atrium walkway exits to the northwest." --northwest 1 --obj1 mamba
python core_room.py --name "x170y-40z0" --short "Heavy undergrowth" --long "Overhanging vines reach down from the ceiling where they have twisted themselves around the network of water sprinklers above. Heavy foliage resulting from the high growth rate of the exotic plants here reach out from beyond the cement path to encroach upon the atrium walkway which you are standing on. \n\nThe only way out is to your east." --east 1 --obj1 baboon
python core_room.py --name "x170y-30z0" --short "A clearing" --long "Overhead, bright solar-panels illuminate the clearing you are in with artificial solar energy. Apart from a few patches of grass, there doesn't seem to be any other plants around. The steel walls of the atrium are warm to the touch, an effect of the solar-panels. \n\nCement walkways disappear into increasing foliage to your north and east. There seems to be a pool of water to your northwest." --northwest 1 --north 1 --east 1 --obj1 python
python core_room.py --name "x170y-20z0" --short "Atrium Walkway" --long "Soft lightpanels cast long bulky shadows everywhere along this walkway. The air feels very wet, and the walkway beneath you feels a bit slippery. Plants on both sides of the walkway seem very unfamiliar to you. Above you is a network of water sprinklers which seem to go off in every direction.\n\nThe plants seem to have dominated the cement path further up northwest. Clearings lie to your south and northeast." --south 1 --northwest 1 --northeast 1 --obj1 python
python core_room.py --name "x180y-10z0" --short "A clearing" --long "This clearing seems to be relatively free of the exotic-looking plants of the atrium. The ceiling here towers over twelve feet high, with bright solar-panels illuminating the whole area. It does seem a mite warm, with the cement walkway beneath your feet feeling hot.\n\nA gust of foul-smelling air is coming from the direction the eastern cement path leads to. The plants seem to get thicker to your south and west. The walkway also extends to the southwest." --west 1 --southwest 1 --south 1 --east 1 --obj1 monkey
python core_room.py --name "x180y-20z0" --short "Heavy undergrowth" --long "Thick, heavy leaves of exotic and unknown plants threaten to swallow you up whole and overwhelm the cement path. The foliage is so abundant that the plants reach all the way to the ceiling, vines entwining along with the water sprinklers to effectively darken the whole area.\n\nBeneath you, the cement walkway leads out north to a clearing." --north 1 --obj1 gorilla
python core_room.py --name "x190y-10z0" --short "Outflow area" --long "Pairs of vertically-arranged metallic tubes jut out of the eastern wall. A strong gush of foul-smelling wind is blowing out of the metallic tubes, presumably the circulated air of the dome. The plants here seem to be extremely well-grown and thick, although they look a little sickly. \n\nThe cement walkway forms a circle here amid the thicket, with a path leading to the west." --west 1 --obj1 boar
python core_room.py --name "x170y-10z0" --short "Heavy undergrowth" --long "The plants in this part of the atrium seem to be enjoying a very high growth rate, for the thicket here is so dense that nothing can possible make its way through the underbrush. The cement walkway seems to have come to an end here, while the abundance of plants everywhere makes this area dark.\n\nThe only way out of this thick undergrowth is east." --east 1 --obj1 panther
python core_room.py --name "x160y-10z0" --short "Heavy undergrowth" --long "Unfamiliar plants and all manner of leaves and large ferns which you have not seen before envelope this area like a skin of greenery. The smell of earth is strong here, and the semi-darkness along with the drops of water condensing on the leaves all around lends this section of the atrium a certain coolness.\n\nThe exit is to the southeast." --southeast 1 --obj1 monkey
python core_room.py --name "x160y-20z0" --short "Pong Area" --long "You stand at the edge of a small pond, only six feet across. The water is crystal clear, and you estimate the depth to be only four feet deep. The pond is circular in shape, its form bordered by a heavy-looking metal circle. All around the pond, unfamiliar plants grow with casual abundance. \n\nThe cement path will take you southeast along an atrium walkway." --southeast 1 --obj1 doe
