#!/usr/bin/env bash
python core_room.py --area north --name "x0y110z0" --short "Section:  South End" --long "You have just entered housing dome #1 through an airlock. This good-sized dome is newly erected which will soon contain housing for mine workers.  You are surrounded by all sorts of construction equipment.  The city is back south.  Proceed north to the housing building." --asouth city --south 1 --north 10
python core_room.py --area north --name "x0y210z0" --short "Central Area" --long "In front of you is the housing building.  Parts of it is under construction but a couple of liveable wings have been developed and can be accessed by going up the turbolift.  You can also check out the northeast quadrant of this floor." --west 10 --east 10 --north 10 --south 10 --northeast 1
python core_room.py --area north --name "x0y310z0" --short "Section:  North End" --long "You are at a northern mass-transit of housing dome #1. If you go north, you will reach the north node that connects to the prison dome and the northern mine.  South leads back to the housing building of this dome." --southeast 1 --south 10 --north 11 --anorth northmasstransit
python core_room.py --area northmasstransit --name "x0y420z0" --short "North Mass-Transit Node" --long "%^CYAN%^+----------%^RED%^D I R E C T O R Y%^CYAN%^------------+\n|                                       |\n|    %^RESET%^%^BOLD%^S%^RESET%^ - Northern Housing Dome%^CYAN%^          |\n|    %^RESET%^%^BOLD%^N%^RESET%^ - Northern Mining Dome%^CYAN%^           |\n|    %^RESET%^%^BOLD%^W%^RESET%^ - Northwest Mass-Transit Node    %^CYAN%^|\n|                                       |\n+---------------------------------------+\n" --asouth north --south 11 --awest northwestmasstransit --west 42 --aeast northeastmasstransit --east 42 --north 17 --anorth northmine
python core_room.py --area northmine --name "x0y590z0" --short "North Mine - Southern Transit Station" --long "Despite the constant cleaning efforts, the maintenance crews have not been able to completely remove the mine soot that has been ground into the floor.  This can be none other than one of The Companys mine domes." --south 17 --northwest 1 --north 4 --obj1 guard --obj2 guard --obj3 captain
python core_room.py --area northmine --name "x0y630z0" --short "North Mine - Ruins" --long  "This was the center of the very busy north mine. Years ago there was an accident that caused a cave-in. The floors are covered in dust and junk and the walls are covered in dirt.\n\nThe mass-transit system continues north for some strange reason while south will take you back to CITY." --south 4 --north 4 --asouth northmasstransit
python core_room.py --area northmine --name "x0y670z0" --short "North Mine - Northern Transit Station" --long "No domes exist north of this point, although a mass-transit station has been built here to accommodate future growth." --southeast 1 --south 4 --obj1 guard --obj2 guard
python core_room.py --area northmine --name "x10y660z0" --short "Guard Barracks" --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --obj1 guard --obj2 guard --northwest 1
python core_room.py --area northmine --name "x-10y600z0" --short "Guard Barracks" --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --obj1 guard --obj2 guard --southeast 1
python core_room.py --area north --name "x10y220z0" --short "Foyer" --long "You are standing in the lobby foyer of the North housing dome. The chamber is wide and furniture arranged sparsely around for people to sit around. A host of light panels above you brightly illuminate the foyer, making the glare of the steel wall panels a bit too much to bear.\n\nThe lobby is to the northeast, while a mass-transit station is located to your southwest." --southwest 1 --northeast 1 --obj1 domeguard --obj2 domeguard
python core_room.py --area north --name "x20y230z0" --short "Lobby" --long "his is the lobby of the North housing dome. The ceiling is quite high, with a small chandelier located in the middle of the room for illumination. At the corners of the lobby are a few chairs, put there by the administration for the benefit of people who just want to sit around doing nothing in particular.\n\nCorridors extend to your north and southeast. To your northeast is the reception, the housing listing office is to your south while the foyer is located to your southwest." --southwest 1 --southeast 1 --south 1 --northeast 1 --north 1
python core_room.py --area north --name "x20y220z0" --short "House Listing And Assignment Office" --long "This rather small office is surrounded by grey steel walls, and you can not help but wonder why the Company does not even try to make it more appealing. From what you gather, here is where a person could peruse the record list of those living in this dome.\n\nTo your north is the lobby." --north 1
python core_room.py --area north --name "x30y220z0" --short "Steel Corridor" --long "you are in a hot corridor which is made out of blank steel walls. The light here is a little too bright, and due to the fact that the air-conditioner seems to have broken down, you find yourself sweating rather profusely. \n\nThe corridor extends to your east, while the lobby is located to your northwest." --northwest 1 --east 1 --obj1 repairdroid
python core_room.py --area north --name "x40y220z0" --short "Steel Corridor" --long "Bright light panels illuminate this corridor, and the light is reflected back to you rather harshly by the steel walls which make up the corridor. Your feet makes loud noises on the steel floor, while you sweat on in the heat.\n\nYou may continue either to your east or west along this hot corridor." --west 1 --east 1
python core_room.py --area north --name "x50y220z0" --short "Steel Corridor" --long "Every step you take clangs loudly on the steel floor beneath you. This steel corridor is not confining, but the stifling heat brought upon by a spoilt air-conditioner system and the metal walls makes it a little unbearable.\n\nThis corridor extends to your east and west." --west 1 --east 1 --obj1 repairdroid --obj2 repairdroid
python core_room.py --area north --name "x60y220z0" --short "Steel Corridor" --long "This is a long corridor with steel walls and steel plates for a floor. You feel rather hot here, a condition brought upon most probably by the errant air-conditioning system in this particular dome. You also notice that it is quite bright here.\n\nThis corridor extends to your west and to your north." --west 1 --north 1 --obj1 northdomeguard
python core_room.py --area north --name "x60y230z0" --short "Steel Corridor" --long "A long corridor with steel as floor, ceiling and walls. Your footfalls echo most eerily here with a certain steely quality to it. All this steel seems to be contributing to the heat building up here as a result of the spoilt air-conditioning.\n\nYou may continue along this corridor by going north or south. To your west is the dome security office." --west 1 --north 1 --south 1
python core_room.py --area north --name "x50y230z0" --short "Security Office" --long "This is a rather dimly-illuminated room. In the semi-darkness, you see a large console, behind which is a few chairs where those in charge of security can monitor the going-ons in the dome via secret cameras. This is a high-security room, and non-authorized personnel can only stay in one corner and not interfere with the situation here.\n\nThe exit is to your east." --item1 console --item1desc "This is a security console which contains monitors used to monitor the going-ons of the dome. Do not even hope to operate it. It is way too complex." --east 1 --obj1 securityofficer
python core_room.py --area north --name "x60y240z0" --short "Steel Corridor" --long "Overtly-bright lights illuminate this steel corridor. The reflections blind your eyes to a certain extent, while the lack of air-conditioning makes you feel a little feverish. This corridor can not be too healthy to stand around in.\n\nYou can continue to the south, east or west along these corridors." --west 1 --south 1 --east 1
python core_room.py --area north --name "x50y240z0" --short "Steel Corridor" --long "The steel walls buffeting the corridor you are in seems to be contributing to the already-heated up atmosphere here. Loud clangs resound all over as your footsteps fall heavily on the steel-plated floors.\n\nCorridors extend to the north and to the east. An old office seems to be to your west." --west 1 --east 1 --north 1 --obj1 maintenancedroid
python core_room.py --area north --name "x40y240z0" --short "Housing Records Office" --long "This office was once used to facilitate the record-keeping of the North Domes residents. Now, with the advent of a new database system which makes the purpose of paper records obsolete, this office has fallen into disuse and has been abandoned and forgotten.\n\nThe exit is to the east. The housing records storage room is located to your south." --south 1 --east 1
python core_room.py --area north --name "x40y230z0" --short "Housing Records Storage" --long "Dust hangs heavily in the air. It appears that there has not been much activity here for a very long time. The room itself is relatively big, and rows of cabinets adorn the walls of the room. Apart from an ancient-looking desk which sits despondently in one corner, the only other furniture here are the cabinets.\n\nYou may leave by heading north." --north 1 --item1 desk --item1desc "Someone once used this table for record-keeping purposes. Now it just sits in one corner, forgotten."
python core_room.py --area north --name "x70y240z0" --short "Steel Corridor" --long "Echoes of your footsteps upon the steel plates which constitute as the floor of this corridor are all over the place. You get the feeling that the situation here is much hotter than it should be, especially since the tell-tale hum of air-conditioners are missing.\n\nTo the east is the dome administration office. Corridors extend to your north and west." --west 1 --north 1 --east 1
python core_room.py --area north --name "x80y240z0" --short "Dome Administration Office" --long "A chill of cold air passes by you. The air-conditioners in this room actually works! As you look around the dimly-illuminated room, you notice that the floor is lavishly covered with a fine red expensive-looking carpet. Light comes from a few rounded lights on the ceiling. At the northern end of this room is a huge oak table, behind which sits the dome administrator when she is working.\n\nThe exit is located to your west. To your east is what appears to be an executive toilet." --west 1 --east 1 --obj1 wendy
python core_room.py --area north --name "x90y240z0" --short "Executive Toilet" --long "You find yourself in a cool toilet which is almost as big as the office outside. A shower stall is by a corner, while at the southern end is a bathtub. The floor is surfaced with black tiles, and you seem to feel that the whole place is a bit too luxurious to be in the North Dome sector.\n\nThe exit is located to your west." --west 1
python core_room.py --area north --name "x70y250z0" --short "Steel Corridor" --long "The bright lights here bears down harshly upon you, and coupled with the reflection on the steel walls, you find yourself caught in a most powerful glare of illumination. The steel plates which make up the floor of this corridor creates steely echoes for your footfalls here.\n\nYou may continue along this corridor by heading south or east." --south 1 --east 1
python core_room.py --area north --name "x80y250z0" --short "Steel Corridor" --long "The steel corridor you are in is made out of steel walls, steel floors and steel ceilings. Along with light panels which make this place unnecessarily bright and a non-functional air-conditioner system, this corridor is hot enough to give anyone a stroke.\n\nThe corridor continues to your west, while an office is located to your east. A store corridor can be reached by going northwest." --west 1 --east 1 --northwest 1
python core_room.py --area north --name "x90y250z0" --short "Plumbing Liaison Office" --long "This is the North Domes plumbing liaison office, the place where residents of this dome report their plumbing woes. It is a rather dull place, with very few furniture. An empty desk sits in the middle of the room, while a closet is located at the eastern end of the office.\n\nYou can leave by going west." --west 1 --obj1 torga
python core_room.py --area north --name "x70y260z0" --short "Store Corridor" --long "You find yourself in a store corridor, a place used by droids to to travel between the other parts of this dome quarter and their storage bays. This place stinks of lubricating fluids, and you detect that the walls and the floors are well-marked with the droids passage.\n\nYou may continue east or west along this store corridor. A steel corridor is located to your southeast." --west 1 --east 1 --southeast 1
python core_room.py --area north --name "x80y260z0" --short "Store Corridor" --long "Wafts of lubrication fluids are everywhere in this area. You can see that droids have used this passage a lot, judging from the amount of scratches on the walls and the abundant track marks on the floor.\n\nTo your north is a droid bay. Otherwise, you can continue west along this corridor." --west 1 --north 1
python core_room.py --area north --name "x80y270z0" --short "Droid Bay 1" --long "You are in a droid bay, the area where droids are stored when they are not on active duty. This room itself is large enough to contain ten droids, the usual number allocated for a droid type to a quarter of a dome. Various zones for each droid are on the floor, and you see a host of mechanical machinery specifically put here to maintain and recharge the droids.\n\nThe exit is to the south." --south 1 --obj1 maintenancedroid --obj2 maintenancedroid
python core_room.py --area north --name "x60y260z0" --short "Store Corridor" --long "This corridor has been thoroughly used by droids, judging from the track marks on the floor and the scratches on the walls. The smell of lubricant fluids is strong in the air, and you get the feeling that more droids than humans use this passageway.\n\nThe store corridor continues to your east. To your north is a droid bay." --north 1 --east 1
python core_room.py --area north --name "x60y270z0" --short "Droid Bay 2" --long "This is one of the North Domes northeastern quarters droid bay, the place where the droids are stored when they are not on duty. Ten zones are located here, enough to store ten droids when they are not working. This bay even has machinery for maintenance and repair purposes pertaining to droid-matters.\n\nYou may leave by going south." --south 1 --obj1 maintenancedroid --obj2 maintenancedroid
python core_room.py --area north --name "x50y250z0" --short "Steel Corridor" --long "Your footfalls echo along this corridor as you walk on the steel plates which constitute as the corridors loor. The bright lights above you bear down too brightly, making you wonder about light control in this dome. You also notice that it is very hot in here.\n\nCorridors lead to your north and south. The North Domes server rooms are to your east and west." --west 1 --north 1 --south 1 --east 1
python core_room.py --area north --name "x60y250z0" --short "Server Room 1" --long "Flickers from LEDs and tiny bulbs illuminate this room. Upon inspection, this place is designed to house a huge computer server. Rows of flashing lights adorn the walls, each light signifying some special thing of which you do not have an inkling of. The server itself is located in the middle of the room, a hulking behemoth of flashing lights.\n\nThe exit is located west." --west 1 --obj1 mei
python core_room.py --area north --name "x40y250z0" --short "Server Room 2" --long "This is a rather dark room, illuminated only by the small flashing lights of the server which stands in the middle of the room. You decide that this room has been specifically designed with the server in mind, as you can clearly see that the server fits into it perfectly, leaving just enough space for people to walk around it.\n\nYou can leave by going east." --east 1 --obj1 bol --obj2 debra
python core_room.py --area north --name "x50y260z0" --short "Steel Corridor" --long "This steel corridor you are in seems to extend forever in an eternity of stainless steel. The walls, ceiling and floor of this area is made of steel, a situation which aggravates the heat problem here brought upon by a non-functional air-conditioner system and the reflectiveness of the steel surfaces.\n\nYou may continue to your north or your south." --south 1 --north 1 --obj1 repairdroid
python core_room.py --area north --name "x50y270z0" --short "Steel Corridor" --long "This corridor you are in is made entirely out of steel, from the walls to the ceiling. Bright light panels above glare down upon you a bit too brightly for your comfort. Due to the lack of air-conditioning, you feel more than a little sweaty standing around here.\n\nThe corridor continues to the south and west." --west 1 --south 1
python core_room.py --area north --name "x40y270z0" --short "Steel Corridor" --long "Steel seems to be the element of the day as you walk along a corridor with steel walls, a steel ceiling and a floor made out of steel plates. Each step you take echo around the corridor courtesy of the sub-hollow steel plating which is the floor.\n\nYou can continue along this corridor to the east or west. The entrance of this domes library is located to your north." --west 1 --north 1 --east 1 --obj1 northdomeguard
python core_room.py --area north --area north --name "x40y280z0" --short "Library Entrance" --long "This is the entrance to the North Dome Library. Apart from the surrounding steel corridor, it has a nice arch as an entrance. Unfortunately, the arch is all that the Company is able to spend on the exterior decor of this place.\n\nThe library can be reached by going east. Otherwise, you may leave by going south." --south 1 --east 1
python core_room.py --area north --name "x50y280z0" --short "Library Counter" --long "You are in a nicely carpetted room. Although the air-conditioning is not working here, you notice that the room is not too hot due to the ceiling fan above you. This is the counter section of the library, where residents of the North Dome who want to borrow or return any library material conduct their transactions.\n\nThe exit is to the west. The library extends to the east." --west 1 --east 1 --obj1 heckle
python core_room.py --area north --name "x60y280z0" --short "Library" --long "Shelves of books surround you on either side of this passageway. Though it is not too large, you can see that the library has a pretty large variety of books. The carpet feels nice beneath your feet, while a ceiling fan above you expels the heat which so plagues this dome.\n\nThe library counter is located to your west. The reading room is to your north, while the library itself extends to your east." --west 1 --north 1 --east 1
python core_room.py --area north --name "x70y280z0" --short "Library" --long "This is the eastern end of a passageway. Here, you notice that the bookshelves are more, taking advantage of the dead-end. A ceiling fan above dispels the heat, while the nice carpet under your feet provide a soft surface to walk on.\n\nThe exit is to your west." --west 1
python core_room.py --area north --name "x60y290z0" --short "Reading Room" --long "This is a reading room. It is very brightly-lit, with many tables and chairs around for those who wish to read. The floor is nicely carpetted, providing a soft touch to those who walk on it. A ceiling fan brings you nice wind from the ceiling.\n\nThe reading room continues to the west. The library is located to your south." --west 1 --south 1
python core_room.py --area north --name "x50y290z0" --short "Reading Room" --long "You are at the western end of the reading room area. Bright lights illuminate this room, bringing a certain shine to the tables and chairs around here. Although the air-conditioning system is not working, a ceiling fan on the ceiling dispels the heat with its much-needed wind.  The exit is to your east." --east 1 --obj1 tom
python core_room.py --area north --name "x30y270z0" --short "Steel Corridor" --long "You find yourself walking along a corridor made entirely out of steel. It is pretty hot in here, especially with the steel walls reflecting the garish light from the light panels above and the lack of air-conditioning in this dome area.\n\nThis corridor extends to the north, east and west." --west 1 --north 1 --east 1
python core_room.py --area north --name "x30y280z0" --short "Steel Corridor" --long "All you can hear here are your footsteps echoed heavily by the steel plates which make up this corridors floor. Together with the almost unbearably hot atmosphere here, you feel that you are starting to get a headache.\n\nYou may continue to your south or northwest." --south 1 --northwest 1
python core_room.py --area north --name "x20y290z0" --short "Steel Corridor" --long "Your passage is buffeted by steel. The steel walls, steel floor and steel ceiling reflect back the bright lighting of the light panels above, making your journey an excessively bright one. Each step you take is echoed along the corridor, an effect of having steel plates for a floor.\n\nYou may continue to the south, southeast and northwest." --southeast 1 --south 1 --northwest 1
python core_room.py --area north --name "x10y300z0" --short "Steel Corridor" --long "You are in a steel corridor, a corridor made completely out of steel. The light panels here seem to be a bit too bright for comfort, and the stainless steel walls just seem to aggravate the problem by reflecting the light. Each step you take echoes loudly all over the place, a situation caused by the steel plates which constitute as the corridors floor.\n\nA mass-transit station lies to your northwest. The corridor continues to your southeast." --southeast 1 --northwest 1 --obj1 northdomeguard
python core_room.py --area north --name "x20y280z0" --short "Steel Corridor" --long "Steel walls, a steel ceiling and a steel floor make up this corridor. In any other place, it would have been an acceptable practice, but the lack of air-conditioning in this dome and excessive bright light panels make this a very hot matter here.\n\nThe steel corridor continues to the north and west." --west 1 --north 1
python core_room.py --area north --name "x10y280z0" --short "Steel Corridor" --long "Your footfalls echo all over the corridor, an after-effect of putting steel plates as flooring. The steel walls reflect the harsh lighting from the panels above, adding to the accumulated heat which has gathered here ever since the air-conditioning system of this dome went down.\n\nThe Public Relations Office of this dome is located to your north. Otherwise, you may continue east or south along this corridor." --north 1 --south 1 --east 1
python core_room.py --area north --name "x10y290z0" --short "Public Relations" --long "This is the Public Relations office of the North Dome. It is very dimly-lit, and you notice a faint waft of aftershave in the air. There does not seem to be much you can see in here. In fact, you wonder how anyone can do any work in this light. However, in the near-darkness, you can make out a table and a chair in the room, no doubt the place where the Public Relations Representative sits when he is here.\n\nThe exit is to your south." --south 1 --obj1 andy
python core_room.py --area north --name "x20y270z0" --short "Steel Corridor" --long "The air-conditioning is definitely not working, for you seem to be sweating excessively from all the heat generated here. The fact that the bright light from the panels on the ceiling are reflected by the stainless steel walls are of no help.\n\nYou can continue along this corridor by heading south or east." --south 1 --east 1
python core_room.py --area north --name "x20y260z0" --short "Steel Corridor" --long "Your loud footsteps are magnified by the steel plates beneath you as you walk along this corridor. Everything here seems to be made of steel, right from the walls to the ceiling. All this metal is giving off a bad heat wave, especially with the air-conditioner system not working at the moment.\n\nThe corridor extends to the north, south and east" --south 1 --north 1 --east 1 --obj1 repairdroid
python core_room.py --area north --name "x30y260z0" --short "Steel Corridor" --long "You seem to be at the eastern end of a corridor. Here the light panels are not as bright as the other parts of the corridor, and you actually feel some respite from the other heated up corridors. All the walls and ceiling are still made out of steel though.\n\nStoreroom are located to your east and south. The corridor continues to your west." --west 1 --south 1 --east 1
python core_room.py --area north --name "x40y260z0" --short "Storeroom" --long "This storeroom is specifically made to accommodate the cleaning and maintenance needs of the droids assigned to upkeep this dome. It is very cramped, with very little space for you to move around. There is nothing here which is of any interest to the ordinary passerby, as only maintenance and repair materials are stored here.\n\nThe exit is located to the west." --west 1
python core_room.py --area north --name "x30y250z0" --short "Storeroom" --long "This small compartment is more of a closet than a storeroom. There is little here for the average resident of Core, for all it contains are maintenance materials for the maintenance droids and certain repair components for the repair droids. There is even a power socket here, but it can only be used by droids.\n\nThe corridor, your only exit out, lies to your north." --north 1 --obj1 repairdroid
python core_room.py --area north --name "x20y250z0" --short "Steel Corridor" --long "A corridor with steel for floor, ceiling and walls, this place is unbearably hot and bright, a condition brought upon by the bright light panels above and the defunct air-conditioner system. Definitely not a place to take a breather.\n\nYou can continue to the north, south or west." --west 1 --south 1 --north 1
python core_room.py --area north --name "x20y240z0" --short "Steel Corridor" --long "Bright illumination comes from the light panels above, lighting up your way more than necessary. Your feet clangs noisily on steel plates which make up the flooring, and you think that you sometimes hear steely echoes of your footsteps along the walls of this corridor.\n\nThe lobby is located to your south, while the corridor extends to your north." --south 1 --north 1
python core_room.py --area north --name "x30y240z0" --short "Reception" --long "The North Dome reception is a roundish room with soft light coming from light panels embedded into the ceiling. A huge table is located here, behind which usually sits the receptionist whos job is to welcome the workers assigned to live in this dome and assign them their quarters. Although the domes air-conditioning system is on the blink, you detect a certain coolness in this area." --southwest 1 --obj1 lil
python core_room.py --area north --name "x10y250z0" --short "Steel Corridor" --long "The steel plates which make up the floor of this corridor echo your footfalls all over the place. The heat here is almost too hot to bear, especially with the walls of the corridor reflecting the light of the bright light panels above.\n\nExits are to the north, south and east." --south 1 --north 1 --east 1 --obj1 northdomeguard
python core_room.py --area north --name "x10y240z0" --short "Steel Corridor" --long "Steel walls border you along this corridor. The lack of air-conditioning cause you to sweat, a condition aggravated by the uncommonly bright lighting of this passageway. Steel metal plates which form the floor cause your feet to echo heavily across the corridor.\n\nThe corridor continues north. To your south is the North Dome Housing Services office." --south 1 --north 1 --obj1 repairdroid --obj2 repairdroid
python core_room.py --area north --name "x10y230z0" --short "Housing Services" --long "The Housing Services office of the North Dome is a rather modest affair. At a glance, it is merely four steel walls surrounding a mere steel table, a few chairs and two cabinets or so. You note that the administration does not care very much about this particular department.\n\nThe exit is to your north." --north 1 --obj1 housingofficer
python core_room.py --area north --name "x10y260z0" --short "Steel Corridor" --long "You find this steel corridor to be confiningly hot, especially with the steel walls reflecting back the garish light from the panels above. The air-conditioner system seems to have broken down, and it does not seem like it is going to be repaired anytime soon.\n\nYou can continue either northwards or southwards." --south 1 --north 1
python core_room.py --area north --name "x10y270z0" --short "Steel Corridor" --long "Steel walls, steel ceiling and steel floor all bear witness to your passing through this corridor. Bright lights above beat their almost-blinding light upon you, while the steel plates which constitute as the floor echo your footfalls all over the corridor.\n\nThe corridor extends to the north and south." --south 1 --north 1 --obj1 repairdroid
