python core_npc.py --name "loser" --label "Loser" --id1 loser --short "Loser" --long "This is a loser.  He is wearing a tight blue tee shirt with matching blue pants and.. hes not on the list!  So he has to wait in the long line, and seems to be getting a bit upset.  You should probably be careful, although with his scrawny figure, you might be able to take him." --level 6 --gender male
python core_npc.py --name "groupie" --label "Groupie" --id1 groupie --short "Groupie" --long "The band groupie eyes you, rubbing his nose while he does.  His hair is disarranged all over his body, and the black death metal shirt he's wearing looks to be about 5 days past due for a wash.  As you watch, he grabs a beer and drinks it, after spilling half on top of his head.  It would be a wise decision to stay away from such an unruly and icky sort of person." --gender male --level 6
python core_npc.py --name "bouncer" --label "Bouncer" --id1 roxbury --id2 bouncer --id3 roxburybouncer --short "Roxbury Bouncer" --long "At first you see only a wall of fabric and muscle.  Then you realize that it is only an arm, and look up into the hard and cruel face of one of the Roxbury's bouncers.  He stares menacingly at you, waiting to punish you for the slightest wrong doing." --gender male --level 12
python core_npc.py --name "cagedancer" --label "Dancer" --id1 cage --id2 dancer --id3 cagedancer --short "Cage Dancer" --long "The dancer's long wavey red hair hangs down to almost her waist, swinging as she dances.  Her outfit clearly shows her muscular body, which she must have worked hard to get and keep.  She winks at you with her green eyes, noticing your admiration." --gender female --level 10
python core_npc.py --name "poledancer" --label "Dancer" --id1 pole --id2 dancer --id3 poledancer --short "Pole Dancer" --long "All legs, this pole dancer sure knows how to move!  By the look of her, shes only about 21. Her long blonde hair flies around her as she moves to the music, seductively moving her hips.  It's no wonder so many guys are gathered around the poles base, drooling." --gender female --level 10
python core_npc.py --name "evilclown" --label "Clown" --id1 evil --id2 clown --id3 evilclown --short "Evil Clown" --long "This is a clown in a black and white clown suit. He has black and white facepaint on and he looks absolutely menacing. His angular jawlines on his face and the creepy painted on smile make him look like he could kill you at any minute." --gender male --level 12 --aggro 1
python core_npc.py --name "bouncer2" --label "Bouncer" --id1 bouncer --short "Bouncer" --long "At first you see only a wall of fabric and muscle.  Then you realize that it is only an arm, and look up into the hard and cruel face of one of the Roxbury's bouncers.  He stares menacingly at you, waiting to punish you for the slightest wrong doing." --gender male --level 12
python core_npc.py --name "slowzombie" --label "Zombie" --id1 zombie --id2 slow --id3 slowzombie --id4 "slow zombie" --short "Slow Zombie" --long "This is a blood thirsty zombie, evil mog is lazy and isn't going to describe it, its slow and its going to eat you" --level 6 --gender bofh
python core_npc.py --name "zombie" --label "Zombie" --id1 zombie --short "Zombie" --long "This is a garden variety run of the mill zombie, wants to eat your brains....nom" --gender bofh --level 6
python core_npc.py --name "vampire" --label "Vampire" --id1 vampire --short "Vampire" --long "This looks like your typical south park goth kid vampire, sparkly light twilight with none of the cool goth like features. Appears to be drinking tomato juice, but it could be blood, but then again it could be tomato juice." --gender other --level 6
python core_npc.py --name "clubdancer" --label "Dancer" --id1 dancer --short "Dancer" --long "This dancer looks like she's strung out on a combination of adrenaline, dopamine and possibly vampire blood. She's wearing a skin tight dress and appears to be enjoying the music." --level 7 --gender female
python core_npc.py --name "vipbouncer" --label "Bouncer" --id1 bouncer --short "Bouncer" --long "This appears to be one of EvilMogs private security guards. They appear to be in a black suit with dark sunglasses, a real high speed shoot to kill type." --level 20 --gender other
python core_npc.py --name "child" --label "Child" --id1 child --short "Child" --long "At first glance this appears to be a 9 year old girl, but as you look closer you realize that the childs eyes are dark and lifeless, their skin pale and white and their clothes tattered and torn. You swear you can see blood dropping from their feet which are floating a few inches above the ground." --level 7 --gender female --aggro 1
