#!/usr/bin/env bash
python core_npc.py --name magnus --label Magnus --short "Magnus" --long "Magnus is a middle-aged cyborg with a large, nasty looking scar running from his left cheek down to his jawbone.  Despite his somewhat rough appearance, he has a friendly sparkle in his eye." --level 1 --gender male
python core_npc.py --name lulams --label Lulams --short "Customs Officer Lulams" --long "Lulams wears a perfectly ironed Company jumpsuit.  Not a wrinkle can be seen.  His hair is sealed beneath a layer of gel half a centimeter thick, ensuring not a single strand of hair will stray from its assigned place." --level 1 --gender male
python core_npc.py --name olasha --label Olasha --short "Olasha the Colony Quartermaster" --long "Olashas Company-issued uniform is hopelessly wrinkled and smeared all over with grease stains.  Her boots are equally mistreated with countless scratches and scuff marks.  Judging by her physical appearance, one would guess she is about middle-age for her species." --level 1 --gender female
python core_npc.py --name lrak --label Lrak --short "Mine Recruiter Lrak" --long "A medium height human male in his mid-20s with sandy brown hair, Lrak looks quite at ease in his Company-issued uniform.  His touch padd, however, is another matter.  He clutches it as if his very life depends on it (which it does, whenever the mining quotas are reviewed)." --level 1 --gender male
python core_npc.py --name mosquito --label Mosquito --short "Mosquito" --long "This huge mosquito has long, tenuous legs that allow it to walk on water, not breaking the surface tension.  It has a long, needle-like bill used to suck the blood of most warm blooded creatures." --level 1 --gender male
python core_npc.py --name sparrow --label Sparrow --short "Sparrow" --long "This little sparrow sings merrily.  He is happy to be in this great park and does not miss his natural predators at all." --gender "male" --level 1
python core_npc.py --name treelizard --label "Tree Lizard" --id1 tree --id2 lizard --short "Tree Lizard" --long "This slippery little tree lizard can change his colors to suit either the dark brown bark of trees, or the bright green of jungle foliage." --level 1 --gender "male"
python core_npc.py --name carrierpigeon --label "Carrier Pigeon" --id1 carrier --id2 pigeon --short "Carrier Pigeon" --long "Driven to extinction centuries ago, this bird is a feat of forensic DNA recovery and engineering.\n\nThis plump bird can be found in most of the Core parks, begging for bread scraps and seed.  These birds have made hats a popular accessory to wear when visiting the parks." --level 2 --gender male
python core_npc.py --name fireant --label "Fire Ant" --id1 fire --id2 ant --short "Fire Ant" --long "This little fire ant looks deceptively harmless.  In truth, this is a hybrid fire ant bred from strains of African fire ants for their high toxicity.  This is not someone to invite to the picnic." --level 2 --gender male
python core_npc.py --name iguana --label "Iguana" --id1 iguana --short "Iguana" --long "This scaly iguana suns herself on a rock.  She looks rather intimidating, but is really not an aggressive creature; she mostly eats insects." --gender female --level 2
python core_npc.py --name rattlesnake --label "Rattlesnake" --id1 rattle --id2 snake --id3 rattlenake --short "Rattlesnake" --long "This rattlesnake looks menacing, but cannot do much harm since its poison sacs have been removed.  He can still bite, so it would be advisable not to annoy him." --level 2 --gender male
python core_npc.py --name ferret --label "Ferret" --short "Ferret" --long "This furry little ferret nuzzles at your ankle as she tries to climb up your pants leg.  You resist the urge to pet the little ferret, knowing she is a wild animal." --gender female --level 2
python core_npc.py --name fieldmouse --label "Field Mouse" --short "Field Mouse" --long "This little mouse squeaks happily as it hides amongst the tall grass.  These little guys have a hard life, constantly being eaten by birds, snakes, and other predators." --gender female --level 1
python core_npc.py --name japanesebeetle --label "Japanese Beetle" --id1 japanese --id2 beetle --short "Japanese beetle" --long "This large japanese beetle scurries about eating other, smaller insects. These beetles are an important part of the food chain here in Shay Park, eating smaller, harmful insects, while itself being eaten by the birds and lizards." --gender female --level 1
python core_npc.py --name "atriumrat" --label "Atrium Rat" --id1 atrium --id2 rat --id3 atriumrat --short "Atrium rat" --long "A failed scientific experiment, this rodent might have originally been intended to be placed within the miniature ecosystem of Shay Park. The creature has a fatal flaw that caused its development program to be scrapped: IT REEKS.  The smell is so bad it would've driven away any and all visitors to the atrium complex.  How it managed to survive and take over the engineering lab is anybody's guess." --level 3 --gender male
python core_npc.py --name "ratqueen" --label "Rat Queen" --id1 rat --id2 queen --id3 ratqueen --short "Rat queen" --long "The biggest of the big and the baddest of the bad, this atrium rat outranks, outsizes and out-stinks them all.  She moves around the lab slowly -- likely because she's pregnant with another litter of her vile spawn (ugh, AGAIN!).  Her fangs and claws look sharp, however, and it appears she knows how to use her size and weight to her advantage in combat." --gender female --level 4
python core_npc.py --name "billy" --label "Billy" --id1 billy --short "Billy, Director of the Office of Environmental Quality" --long "Billy is a rather unpopular employee here at the Company.  With society's hostile contempt towards tobacco smoking, Billy's unfathomable cigarette addiction is not well received.  He has been threatened several times by his boss to quit or be fired.  However, the truth of the matter is, it is difficult to find competent managers that will live on a barren mining colony like Core.  Unless that changes, Billy will continue to smoke like a smokestack and still retain his job." --gender male --level 9
python core_npc.py --name "hans" --label "Hans" --id1 hans --short "Hans, the Director of Employee Affairs" --long "No one knows more about having affairs with employees than the lecherous Hans!  Hans finds that the teary eyed women who come to his office complaining about being sexually harassed by her co-workers needs much comfort and consoling.  This usually involves a bottle of chilled chardonay and some oysters." --gender male --level 10
python core_npc.py --name "freddy" --label "Freddy" --id1 freddy --short "Freddy, the Director of Sanitation Engineering" --long "Freddy's title may be misleading.  He is not an engineer.  In fact, he never even graduated from high school.  Freddy secured his executive position because he was the only person who did not realize Director of Sanitation Engineering is a euphemism for garbageman.  Ignorance is bliss." --gender male --level 9
python core_npc.py --name "biddleman" --label "Biddleman" --id1 biddleman --short "Mrs. Biddleman, the Director of Supply Distribution Logistics" --long "No one, not even the Human Resources Department, knows Mrs. Biddlemans first name.  No one has ever seen her husband either or even confirmed that she is married.  Her pinched face peers out at you through horn rimmed glasses with a mixture of annoyance and disgust.  You wonder if getting a new stapler is worth dealing with this thoroughly unpleasant hag." --gender female --level 10
python core_npc.py --name "manny" --label "Manny" --id1 manny --short "Manny, the Director of Colony Ethics" --long "In an ironic twist of fate, Manny landed this job just after being released from prison on embezzlement charges back on Earth.  He applied for the job not thinking he would be awarded it, however his background check information got lost and the next starship to Core was leaving the next day, and well, here he is now.  He really has tried to perform his job well and no one at The Company has ever suspected his shady background." --gender male --level 10
python core_npc.py --name "clerk" --label "Clerk" --id1 clerk --short "A Complaint Department Clerk" --long "A bored and disgruntled clerk who has been assigned to record down all the complaint reports from the employees and later pass it on to the proper people involved. His dishevelled clothes and untidy hair indicate a lack of personal grooming. This clerk doesn't seem to want to be here. Somehow, you suspect that this post isn't exactly an enviable one." --gender male --level 9
python core_npc.py --name "officer" --label "Officer" --id1 officer --short "A Complaint Officer" --long "Suspicious eyes look at you as you size up the Complaint Officer. This Vaurgch has been stationed here in case any of the people making complaints get too overenthusiastic. He doesn't talk at all. In fact, all he does is stand here. But cause too much trouble at this department and you can be guaranteed of a severe reprimand from this Complaint Officer." --gender male --level 10
python core_npc.py --name "rachel" --label "Rachel" --id1 rachel --short "Nurse Rachel" --long "You see a fat muscular woman in her forties. Her white nurse uniform seems to be extremely tight-fitting, with folds of fat jutting out at regular intervals of her body. Her matronly look is disguised by the fact that deep in her heart, she is a sadistic woman who enjoys nothing more than the suffering of her patients. Ever since she was transferred from Earth to Core, she has been cut off from her usual doses of suffering. Now, all she can do is find satisfaction in the meager daily pains of the employees on this planet." --gender female --level 8
python core_npc.py --name "valerie" --label "Valerie" --id1 valerie --short "Valerie, Employee-Management Liaison Officer" --long "Valerie is a very pretty nympho. Her curvaceous curves, well-toned body and smooth white skin have been known to turn on the female, male and neuter genders of all races. The Company has stationed her here in the hope that she can handle all employee-related problems without ever involving the management. So far, they have been more than successful in this endeavour. It seems that more often than not, Valerie manages to settle the problem herself, through channels best left unmentioned." --gender female --level 10
python core_npc.py --name "norman" --label "Norman" --id1 norman --short "Director Norman" --long "Director Norman is the man in charge of the Company's dealings in information and intelligence. His tall, thin and pale form might not be much to look at, but Norman is one of the most cunning businessman in Core. His field gives him free rein of the information in possession of the Company, and armed with this knowledge, he is able to make very profitable decisions apart from the usual information business of the Company over which he presides. A man of very few words, since Norman himself is aware that anything he says can be counted as information. And he intends to make a sale on every piece of info he lets out." --gender male --level 9
python core_npc.py --name "jacob" --label "Jacob" --id1 jacob --short "Safety Director Jacob" --long "A tall, slender balding man with a goatee, Jacob is the person who's in charge of safety on Core. His slow steady step shows a state of mind which is calm, and you notice that his slow calculated speech is indicative well-thought out responses to each question and sentence. In reality, Jacob is a very careful man, the ideal candidate for the directorship in this department. His responsibilities include planning out and evaluating safety procedures for the Company." --gender male --level 10
python core_npc.py --name "wendall" --label "Wendall" --id1 wendall --short "Mr. Wendall, Duchies ex-secretary" --long "Wendall is one of those guys that makes every other male around him feel inadequate.  Meanwhile, the women practically rip off all their clothes and beg him to pleasure them.  Somehow, Vice President Duchie persuaded Wendall to take the humble position of secretary.  Somehow." --level 8 --gender male
python core_npc.py --name "antoinnete" --label "Antoinnette" --id1 antoinnette --short "Antoinnette, Company Morale Officer" --long "Antoinnettes delicate French looks conceal the hyperactive nympho inside. A nympho who had one gene too many engineered into her during her creation, this female has been bursting with energy ever since the first day she stepped off the production line. The Company has seized the opportunity to enlist her as Core's Morale Officer, where her energy is put to very good use organizing events, planning stuff and even the occasional entertainment for the employees." --gender female --level 11
python core_npc.py --name "droid" --label "Enforcement Droid" --id1 droid --id2 enforcement --id3 enforcementdroid --short "Enforcement droid" --long "The enforcer droid is a thin, reedy-looking mechanical humanoid. It is not hard to dismiss it as the weakest of all the Core Enforcement robots, for its steel frame is nearly skeletal and there doesn't seem to be any form of strength about it. Most enforcer droids are given relatively mundane tasks, which range from preventing unauthorized personnel from entering restricted areas to sentry duty." --gender neuter --level 11
python core_npc.py --name "grunt" --label "Enforcement Grunt" --id1 grunt --id2 enforcement --id3 enforcementgrunt --short "Enforcement grunt" --long "This evil-looking vaurgch is one of Enforcements muscles, the brawn which is sent in to deter would-be criminals from carrying out their crimes. The grunt wears a tight-fitting blue uniform with intermittent stripes of yellow. A few red specks, looking suspiciously like blood, adorns the front of the uniform. At the moment, this grunt is stationed here to guard the area and to prevent anymore incidents from happening. Enforcement grunt has no missing limbs." --level 14 --gender male
python core_npc.py --name "analyst" --label "Enforcement analyst" --id1 analyst --id2 enforcement --id3 enforcementanalyst --short "Enforcement analyst" --long "The enforcement analyst is a one of the special taskforces set up by Enforcement for cases which require detective work and brainpower. Her main job would be to visit the scene of the crime and investigate the entire place thoroughly for clues. She is wearing the typical blue Enforcement uniform with a yellow patch on her left shoulder indicating that she belongs to the analysis team." --gender female --level 12
python core_npc.py --name "tech" --label "Reactor Tech" --id1 tech --id2 reactor --id3 reactortech --short "Reactor Tech" --long "Clad in simple white and yellow coveralls, this Artris reactor tech is just one of the many technicians whose daily duty is to oversee the well-being of the immense fusion generator. With his four arms, this tech is able to complete most jobs in half the time it takes other two-armed races to finish them. However, although highly trained in technical skills and in possession of great accuracy, the tech is relatively introverted and is a bit on the quiet side." --gender male --level 12
python core_npc.py --name "kendall" --label "Foreman Kendall" --id1 kendall --id2 foreman --short "Foreman Kendall" --long "Foreman Kendall is the person who answers directly to the higher-ups regarding the fusion generator here. He is a plain-looking man, but the evil glint in his eyes betray a mind which is both devious and relentless. Having worked his way up from a normal reactor tech, Kendall now enjoys the privileges of a foreman - which also includes a very difficult time when the generator gets blown up." --gender male --level 13
python core_npc.py --name "carson" --label "Engineer Carson" --id1 engineer --id2 carson --short "Engineer Carson" --long "Fat, sweaty and balding, Engineer Carson is the epitome of a man who is in serious need of exercise. Carson was once a pretty lean man, but too much sitting and an obsessive liking for sugar-coated chocolate doughnuts have piled up the fat on him. He is a representative of City Engineering - one of their less docile ones, and he's hanging around here to protect the City Engineers' interests. Naturally, being a City Engineer has made him more than a little pompous." --level 13 --gender male
python core_npc.py --name "james" --label "Paymaster James" --id1 james --id2 paymaster --id3 paymasterjames --short "James Russell, Paymaster" --long "A rather bloated man with dark skin, James can be a slick-talking character... if he thinks you're worth it. Otherwise, you're way below his attention. However, there has been rumours lately that he has been using his position as Paymaster to relocate some Company funds. To date, no one's been able to prove anything, but certain parties in the Company would be more than glad to see the end of him here. "  --gender male --level 14
python core_npc.py --name "eric" --label "Payroll investigator" --id1 eric --id2 "payroll investigator" --id3 payroll --short "Eric Douly, Payroll investigator" --long "A skinny little guy, with greasy hair and a small beard. He looks to have worked himself to death, or that he just doesn't care about his job. He is known for having found slackers in the company by checking the payroll reports. His uniform looks worn down and dirty as if he hasn't showered in days, if not weeks.  He grins at you and wonders if you'll ever be asking about the slackers he's found lately. " --gender male --level 15
python core_npc.py --name "kavi" --label "Payment Clerk" --id1 kavi --id2 "payment clerk" --id3 payment --short "Kavi, Payment Clerk" --long "Constantly under the watchful eyes of Company inspectors, this poor nympho has been turned into an extreme submissive. She never speaks, doesn't look at anyone at all and when spoken to will hardly answer. There's the look of a trapped animal in her eyes, the sign of someone who lives in constant fear of being caught making a mistake. Because of that, she pays a hundred percent attention and more to her work." --gender female --level 13
python core_npc.py --name "horace" --label "Horace" --short "Horace Clancy the Company Accounts Inspector" --long "Having lost his arm in an accident when he was young, Horace grew up with cybernetic limbs and the advantages which came with them. In short, he became a bully. However, he did not neglect his mental faculties, and years of diligent study have produced a sharp and mentally alert man with the strength only artificial limbs can give. Horace has muscled his way into the post of Company Accounts Inspector because he finds the mental stimulation of checking payments interesting. The fact that he occasionally administers lessons to errant payment clerks is overlooked only because this department has to be one of the Company's most efficient ones." --gender male --level 14
python core_npc.py --name "monzema" --label "Monzema" --short "Monzema, Recordkeeper" --long "Monzema is a very old critin. After moving out of the underground burrows he originated from, Monzema slowly developed his sight before discovering his love for reading. This passion finally peaked when the Company offered the post of Recordkeeper on Core to him. Now, with his pair of spectacles, Monzema manages the archiving of accounting records in this department. Although the files aren't exactly prime reading material, Monzema is happy enough here. He of course still wishes to be made a librarian someday, but for an old critin, that day might not never come." --level 13 --gender male
python core_npc.py --name "josef" --label "Josef" --short "Financial Controller Josef Puldonsky" --long "Steely eyes look back at you as you appraise this man. Josef Puldonsky is a bear of a man, measuring about six feet in height. A slight paunch indicate a lack of exercise, but this is overshadowed by the fact that this man is not only a shrewd businessman, but also one of the Company's best when it comes to financial matters. The Financial Controller's job on Core is not an easy one, but Josef is definitely the man for it. His eyes betray no trace of his current emotional status, only a cold and calculating look. Josef has no missing limbs. " --level 15 --gender male
python core_npc.py --name "jenny" --label "Jenny" --short "Jenny Thackery, HR Director's Personal Secretary" --long "An aura of professionalism surrounds this 32-year-old woman. Short-cropped red hair, an elegantly conservative dress with minimal makeup and jewelry all come together to portray the ultimate working woman image. No one knows much about Jenny except that she was just transferred over from Earth recently. So far, she hasn't been winning any popularity awards due to her tough character and her stern attitude. The HR Director himself is wondering if he should perhaps transfer her over to some other department, like maybe Enforcement... " --level 16 --gender female
python core_npc.py --name "edwardio" --label "Edwardio" --short "Edwardio the Director of Human Resources" --long "You're a bit surprised to find that the Director of Human Resources is in fact a liktah and not a human, but after awhile you realize why the Company chose him. Edwardio is a happy person with a permanent grin on his face. He's constantly cracking jokes, but deep inside he's more than just a good entertainer. In fact, he's one of the best mediators around, and when the situation calls for it, he can get professional and sensitive to others' feelings. But right now, Ed is in his usual happy mood as he bustles around his office merrily. " --gender male --level 14
python core_npc.py --name "vern" --label "Vern" --short "Supervisor Vern" --long "A short stocky man, Vern is a pretty silent guy whose job is to make sure that everyone in this department does his or her work properly. He is very much learned in the ways of HR, and probably knows more about what to do here than anyone else in this deparment, having worked here ever since he could. Vern never moves from his place, and when he does move it's only when he has to go to the toilet or for lunch. " --gender male --level 15
python core_npc.py --name "boa" --label "Sewer Boa" --id1 sewer --id2 boa --id3 sewerboa --short "Sewer boa" --long "Like the ones in the Amazon, this sewer boa kills its victims by crushing their bones. Right now, it's looking at you like you might be next. The cold-blooded eyes following your every move is quite unnerving. Don't hang around too long." --level 5 --gender female
python core_npc.py --name "snake" --label "Water Snake" --id1 water --id2 snake --id3 watersnake --short "Water snake" --long "This thin water snake is just snaking around in the waters, looking for prey like rats and such. It won't bother you." --gender male --level 5
python core_npc.py --name "greensnake" --label "Green Water Snake" --id1 green --id2 snake --id3 watersnake --id4 greenwatersnake --short "Green water snake" --long "The thin form just below the surface of the waters is a water snake. Its green skin camouflages it well under the murky sewer waters. Though not poisonous like its sea counterparts back on Earth, it might prove a danger if provoked. " --level 8 --gender female
python core_npc.py --name "constrictor" --label "Sewer Constrictor" --id1 sewer --id2 constrictor --id3 sewerconstrictor --short "Sewer constrictor" --long "Beady eyes look at you as the sewer constrictor slowly unfolds its long body from somewhere in the water under you. It is hungry, but it's not about to attack you. Yet. " --level 7 --gender male
python core_npc.py --name "cockroach" --label "Cockroach" --short "Cockroach" --long "Smelly and small, this thing is running around the sewers, spreading its own brand of germs and viruses around. Compared to the amount of germs around here, it isn't doing much but then again, it's vermin. It should be killed. " --level 6 --gender male
python core_npc.py --name "monitor" --label "Dozing Monitor Lizard" --id1 monitor --id2 lizard --id3 monitorlizard --short "Dozing monitor lizard" --long "Normally a highly-efficient and fast predator, this monitor lizard appears to be dozing away. Its dark shiny skin is glistening, but you're not even inclined to test and feel the texture of its body. Monitor lizard has no missing limbs." --level 8 --gender male
python core_npc.py --name "wasteworm" --label "Wasteworm" --id1 worm --id2 wasteworm --short "Wasteworm" --long "Measuring only a metre long, this native of the sewage waste is a sort of evolved slug. Now, with its single eye and jaw, it seems intent on tearing you apart! " --level 6 --gender neuter
python core_npc.py --name "shelledheptosquid" --label "Shelled heptosquid" --id1 heptopsquid --id2 shelledheptosquid --id3 squid --short "Shelled heptosquid" --long "Large bulbous eyes peer at you from the surface of the murky waters. A long carapaced form, whitish in color, slides through the water before you can get a good glimpse of what it is. The sensation of a lot of tentacles sweeping against your feet under the sewer waters makes your skin crawl. Maybe you should get out of the water. Fast. " --level 7 --gender neuter
python core_npc.py --name "heptosquid" --label "Heptosquid" --id1 squid --id2 heptopsquid --short "Heptosquid" --long "Little can be seen of the heptosquid, what with the dark murky waters and its soft near transparent body. All you know is that you can see a number of tentacles flailing around its 2-meter long body. You don't want to go anywhere near this thing. " --gender neuter --level 6
python core_npc.py --name "drone" --label "Engineering drone" --id1 drone --id2 engineering --id3 engineeringdrone --short "Engineering drone" --long "The engineering drone is an automated unit which is capable of making minor repairs to quite a number of faults in the sewers. Working on information transmitted to it from the main sewer engineering control centre, it'll analyse the problem and then set out to rectify it." --level 7 --gender neuter
python core_npc.py --name "probe" --label "Sewer Probe" --id1 probe --id2 sewerprobe --id3 sewer --short "Sewer probe" --long "This is a sewer probe, a robot designed especially to help sewer engineers maintain the sewers in good condition. Its main duty is to go around the sewers and send back recorded information of any faults to the main control room of the sewer engineers. It is able to access any place in the sewers, considering the fact that it moves around on a hover unit. Sewer probe has no missing limbs. " --level 6 --gender neuter
python core_npc.py --name "maxim" --label "Maxim Rogers" --id1 maxim --id2 maximrogers --short "Sewer Engineer Maxim Rogers" --long "This is Maxim Rogers, a nympho who has worked very hard to get where she is now. By far, she is one of the more intelligent nymphos around. Although she has long neglected her looks for a more intellectual purpose, you can see that this petite lady with shoulder-length auburn hair is muscularly shapely where it counts. She can't be over 25 years of age, but you can see that years of serious study of the sewers and other intellectual matter has taken a slight toll on her. " --gender female --level 10
python core_npc.py --name "rat" --label "Rat" --id1 rat --short "Rat" --long "Dirty and smelly, this large rat is looking at you hungrily. You suddenly realize that food is hard to come by in the sewers. " --level 6 --gender male
python core_npc.py --name "queenslug" --label "Queen Slug" --id1 queen --id2 slug --short "Queen slug" --long "Black stripes adorn the body of the main slug herself. The normally pinkish body is yellow, while the slime around her is a glistening orange. This is the queen slug, and you have trespassed into her own private kingdom. " --gender female --level 8
python core_npc.py --name "watersnake" --label "Water Snake" --id1 water --id2 snake --id3 watersnake --short "Water snake" --long "This thin water snake is just snaking around in the waters, looking for prey like rats and such. It won't bother you. " --level 6 --gender female
python core_npc.py --name "largeheptopsquid" --label "Large Heptosquid" --id1 squid --id2 heptosquid --id3 largeheptosquid --short "Large Heptosquid" --long "The huge eyes staring at you from out of the waters is not artificial... you're actually looking at a very large heptosquid. The fat tentacles are all around and the body looks solid, like there's an extra layer of thick skin on it. You might find this to be a dangerous adversary indeed. " --gender neuter --level 7
python core_npc.py --name "arnie" --label "Arnie" --short "Arnie" --long "Wild eyes look at you from behind long dishevelled hair. Arnie's face is covered with wrinkles which contorts the old hermit's face whenever he smiles nervously. The stink which he is exuding is enhanced by the bundled clothes covering his body, clothes which you doubt have ever been washed. " --gender male --level 12
python core_npc.py --name "salik" --label "Sewer Engineer Salik" --id1 salik --id2 sewer --id3 engineer --short "Sewer Engineer Salik" --long "Clad in a non-descript green and blue sewer maintenance uniform is a thin abernon sewer engineer. You notice from his nametag that his name is Salik, and realize that he must be here to take a look at some of the documents left in this place. His hideous face does not even betray the slightest notice of your presence when you entered. You conclude that he must either be very busy or very arrogant. " --gender male --level 12
python core_npc.py --name "slug" --label "Slug" --short "Slug" --long "Leaving slime around it, this wormlike creature is moving slowly but surely across the walls of the room. It may seem defenceless, but you're sure that its bulk hides its defensive capabilities." --level 6 --gender neuter
python core_npc.py --name "warrior" --label "Warrior Rat" --id1 warrior --id2 rat --id3 warriorrat --short "Warrior Rat" --long "Much bigger than your average rat, this fierce-looking rodent has battle scars all over its body, the veteran of many battles with the rats. Among its vermin kin, this particular rat is very much feared and respected. " --gender female --level 8
python core_npc.py --name "leader" --label "Rat Leader" --id1 rat --id2 leader --id3 ratleader --short "Rat Leader" --long "Large, way much larger than even the warrior rats is this black evil-looking creature. A sharp snout sniffs royally at you as it gets a scent of the lowly creature before it. This majestic rodent is the ruler of the rats in this area. Here, its royal squeak is LAW. Don't cross it." --gender female --level 9
python core_npc.py --name "queenslug" --label "Queen Slug" --id1 queen --id2 slug --id3 queenslug --short "Queen Slug" --long "Black stripes adorn the body of the main slug herself. The normally pinkish body is yellow, while the slime around her is a glistening orange. This is the queen slug, and you have trespassed into her own private kingdom. " --gender female --level 9
python core_npc.py --name "slime" --label "Slime" --id1 blob --id2 slime --short "blob of living slime" --long "All you see is a large amount of slime gathered in an area of the room. You can see through it, the ooze being transparent. This must have been one of the Company's failed experiments, stored away in a corner of the sewers, never to be seen again." --gender neuter --level 9
python core_npc.py --name "log" --label "Alligator" --id1 alligator --id2 log --short "log floating in the sewer waters" --long "This appears to be an alligator which has sated its hunger on the other poor unfortunate residents of the sewers. Now it is asleep, no doubt to awaken again later when it's hungry. You sure don't want to be here when that happens." --gender male --level 8
python core_npc.py --name "johnson" --label "Sewer Engineer Johnson" --id1 johnson --id2 sewer --id3 engineer --short "Sewer Engineer Johnson" --long "This 6-foot cyborg with a body almost totally encased in metal has been examining the condition of this room. The cyborg, who is called Johnson according to the nametag on its partially metal chest, looks up at you as you enter with cold calculating eyes before continuing on his work. You realize that he must have been chosen to work in this purportedly dangerous area due to his immense strength." --gender male --level 12
python core_npc.py --name "tangleweed" --label "Tangleweed" --id1 tangle --id2 weed --id3 tangleweed --short "Tangleweed" --long "At the moment, the tangleweed is not moving. But eyeing the hooks on the weeds vines, you are sure that it is an adequate predator when it comes to a fight. This is one plant you don't want to tangle with." --gender neuter --level 4
python core_npc.py --name "snapperjaw" --label "Snapperjaw" --id1 snapper --id2 jaw --id3 snapperjaw --short "Snapperjaw" --long "A mutated version of the native Earth sunflower, the snapperjaw will not hesitate to shred any living thing which happens to get into range of its huge serrated jaws. You'll want to be careful around this plant." --level 5 --gender neuter
python core_npc.py --name "fern" --label "Giant Fern" --id1 giant --id2 fern --id3 giantfern --short "Giant Fern" --long "A huge towering plant, you notice that this native species of Earth has evolved into a more complex lifeform. Not only is it semi-sentient now, but it is also capable of defending its ownself against offensive lifeforms, a necessity in the hostile conditions of the atrium." --level 6 --gender neuter
python core_npc.py --name "pottles" --label "Pottles the gerbil" --id1 pottles --id2 gerbil --short "Pottles the gerbil" --long "A small light brown furry gerbil. He has a white tummy, and very sharp claws. He is very cute, and quite friendly but scared of strangers. He will probably run from you if you come near him." --level 12 --gender male
python core_npc.py --name "floorvine" --label "Floorvine" --id1 floor --id2 vine --id3 floorvine --short "Floorvine" --long "This vine on the floor looks harmless enough, but you recognize it as belonging to a mutated species of plants from Earth which is capable of defending itself against attacks from other beings." --level 4 --gender neuter
python core_npc.py --name "blob" --label "Dark Blob" --id1 dark --id2 blob --id3 darkblob --short "dark blob" --long "A blob of dark matter is moving nearby. As it is basically shapeless, you assume that this is a form of mutated lifeform due to the unnatural tentacles which appear to be trailing in the water from under it. It doesn't seem to be hostile, and it doesn't even seem to notice that you are here." --gender neuter --level 8
python core_npc.py --name "planner" --label "Financial Planner" --id1 financial --id2 planner --short "Financial Planner" --long "He looks to be human wearing black slacks and a white shirt, a pocket protector full of pens can be seen on his shirt.  His id tag says financial planner on the bottom." --level 17 --gender male
python core_npc.py --name "jeff" --label "Jeff" --id1 worker --id2 jeff --id3 officeworker --short "Jeff the office worker" --long "This is an average office worker, he is dressed in black slacks and a white button up shirt." --level 18 --gender male
python core_npc.py --name "rick" --label "Rick" --id1 rick --id2 financial --id3 planner --id4 financialplanner --short "Rick the financial planner" --long "This is rick, he is a financial planner, he is dressed in black slacks and a white button up shirt. Various tattoos can be seen on his thick muscled arms." --level 17 --gender male
python core_npc.py --name "peter" --label "Peter" --id1 peter --id2 manager --id3 financemanager --short "Peter the finance manager" --long "This is Peter the finance manager, he is a tall human wearing black slacks a white button up shirt, and a black tie.  He has thick muscled tattood arms." --level 18 --gender male
python core_npc.py --name "ken" --label "Ken" --id1 ken --id2 analyst --id3 stock --id4 stockanalst --short "Ken the stock analyst" --long "This is Ken, he is a stock analyst.  He looks to be wearing blue slacks and a white button up shirt.  His arms appear to be tattood." --level 17 --gender male
python core_npc.py --name "brian" --label "Brian" --id1 brian --id2 analyst --id3 stock --id4 stockanalst --short "Brian the stock analyst" --long "This is Brian, he is wearing blue slacks, a white button up shirt and a blue tie.  His neck and arms appear to be tattood." --level 18 --gender male
python core_npc.py --name "craig" --label "Craig" --id1 craig --id2 office --id3 manager --id4 officemanager --short "Craig the office manager" --long "He appears to be a tall human, he is dressed in black slacks and a white button up shirt.  He looks muscled and angry." --level 18 --gender male
python core_npc.py --name "bob" --label "Bob" --id1 bob --id2 worker --id3 office --id4 officeworker --short "Bob the office worker" --long "This is an angry office worker, he is wearing torn slacks and a dirty button up shirt. He appears to be extremely busy." --level 18 --gender male
python core_npc.py --name "mike" --label "Mike" --id1 mike --id2 worker --id3 office --id4 officeworker --short "Mike the office worker" --long "This is an average office worker, he is wearing slacks and a button up shirt.  He appears to look very busy." --level 17 --gender male
python core_npc.py --name "john" --label "John" --id1 john --id2 worker --id3 office --id4 officeworker --short "John the office worker" --long "This is an average office worker, he is wearing slacks and a button up shirt.  He appears to look very busy." --level 18 --gender male
python core_npc.py --name "tawny" --label "Tawny" --id1 tawny --id2 secretary --short "Miss Tawny, Greys secretary" --long "This is the beautiful Miss Tawny, whom Grey had transferred here all the way from Earth.  She is a well endowed blonde of Nordic descent who does her job efficiently.  She has many talents, many of which, it is rumoured, Grey has experienced first hand.  As scarce as women are on Core, the gentlemen can rest assured that Miss Tawny has no monogamous hang ups." --level 4 --gender female
python core_npc.py --name "sewerboss" --label "Sewer Boss" --id1 sewer --id2 boss --id3 sewerboss --short "Sewer Boss" --long "This appears to be some sort of genetically modified humanoid, its clothes appear to be made of the skin of its enemies and it appears to be dripping in blood." --level 8 --gender male