#!/usr/bin/env bash
python core_npc.py --name "guard" --label "Guard" --short "Mine Guard" --long "The burly guard has been stationed here to make sure that nobody steals the valuable ore in the mine." --gender male --level 8
python core_npc.py --name "captain" --label "Mine Guard Captain" --id1 mine --id2 guard --id3 captain --id4 mineguard --id5 mineguardcaptain --id6 guardcaptain --short "Mine Guard Captain" --long "The Captain gives you a don't mess with me look and then casually gestures for you to move along.  His feline legs look very powerful, probably from spending many years stationed at The Companys branch office on the Blit homeworld before being re-stationed to Core." --level 16 --gender male
python core_npc.py --name "domeguard" --label "Dome Guard" --id1 dome --id2 guard --id3 domeguard --short "Dome Guard" --long "Tall and well-built, this armored man is one of the elite guards who have been assigned to enforce the Companys rules in the Northern housing dome. The green armor embedded into his clothes provides the guard a good measure of protection, and the visor which protects his face hides his expression from you. All you see is a stern-lipped mouth bordering on a sneer. Keep out of trouble, and this imposing figure won't take any notice of you. North Dome guard has no missing limbs." --level 7 --gender male
python core_npc.py --name "repairdroid" --label "Repair Droid" --id1 repair --id2 droid --id3 repairdroid --short "Repair Droid" --long "Whirs and clicks greet your ears as you move nearer to the repair droid for a better look. The black shiny surface of the mechanical creature is bristling with various steel appendages, mostly outfitted repair equipment. There doesn't seem to be any visual devices by which the droid can see, but it does appear that it is more than capable of finding its way around and repairing damaged stuff." --level 7 --gender neuter
python core_npc.py --name "northdomeguard" --label "North Dome Guard" --id1 north --id2 dome --id3 guard --id4 northdome --id5 domeguard --id6 northdomeguard --short "North Dome Guard" --long "Tall and well-built, this armored man is one of the elite guards who have been assigned to enforce the Companys rules in the Northern housing dome. The green armor embedded into his clothes provides the guard a good measure of protection, and the visor which protects his face hides his expression from you. All you see is a stern-lipped mouth bordering on a sneer. Keep out of trouble, and this imposing figure will not take any notice of you." --level 8 --gender male
python core_npc.py --name "securityofficer" --label "Security Officer" --id1 security --id2 officer --id3 securityofficer --short "Security Officer" --long "Dressed in a light blue uniform, this security officer is responsible for maintaining the controls in the security office which you are in. A navy blue securiy cap is on his head, shielding part of his face from you. There seems to be an air of intensity around him, as if he is concentrating hard on his duty. A whiff of not-too-cheap cologne brushes pass your nose as he moves around." --level 8 --gender male
python core_npc.py --name "maintenancedroid" --label "Maintenance Droid" --id1 maintenance --id2 droid --id3 maintenancedroid --short "Maintenance Droid" --long "This white droid is essentially a mechanized janitor. It is a squat-looking affair, tracks instead of legs and maintenance apparatus instead of hands. Its bulky torso is caused by it having to lug around most of its cleaning materials, from water to cleaning fluid. Although it is rather wide, you see that its tracks have been specially designed to provide maximum moving space." --level 7 --gender neuter
python core_npc.py --name "wendy" --label "Wendy" --id1 wendy --id2 dome --id3 admin --id4 domeadmin --short  "Wendy the dome admin" --long "Long straight hair tied back neatly, the woman before you is professionalism in human form. Every inch of her screams corporateness, from her immaculate executive suit right down to her unsmiling beautiful face. Steely eyes evaluate you as you in turn look over her, and you get the feeling that she doesn't take lightly to be looked over. Wendy is the corporate lady in every sense, as you detect a capacity to smile and be nice when she has to, but only when it is necessary. Otherwise, all you will ever get from her is a cold hard stare." --level 9 --gender female
python core_npc.py --name "torga" --label "Torga" --id1 torga --id2 plumbing --id3 liason --id4 plumbingliason --short "Torga, Plumbing Liaison" --long "This huge, hulking specimen of a vaurgch is the North Domes plumbing liaison. Even from where you are standing, you can actually smell him. There is a dirty look about Torga, and you note that the streaks of black dirt on his skin have most probably been there for about a week or so. Being the one who handles all of the North Dome's residents plumbing problems, Torga spends a lot of time in the sewerage. And you can also smell that fact out." --level 8 --gender male
python core_npc.py --name "mei" --label "Mei" --id1 server --id2 tech --id3 mei --id4 servertech --id5 techmei --id6 servertechmei --short "Server tech Mei" --long "Thin and pale, Mei is one of those few people who are responsible for keeping the North Domes computer systems running. Lack of proper food and days spent perpetually in front of computer monitors has reduced this once spunky girl to a thin shadow of her former self. Dark rings under her eyes are testimony to the late nights spent maintaining the server, and a certain haggardness seem to hang over her like a dark cloud. She is so thin and anorexic, she actually seems to be two-dimensional." --level 7 --gender female
python core_npc.py --name "bol" --label "Server tech Bol" --id1 server --id2 tech --id3 bol --id4 servertech --id5 techbol --id6 servertechbol --short "Server tech Bol" --long "You find yourself looking at an extremely unattractive female blit. Her long hair is all messed up, and her sour face only serves to further uglify her. A well-rounded torso bulges out under her white techcoat, and you look away when you notice that the labcoat is so short that it reveals certain undesirable elements. Bol seems to hate people, a trait which you deduce from the way she snaps at everyone who comes into the server room." --level 9 --gender female
python core_npc.py --name "debra" --label "Server tech Debra" --id1 server --id2 tech --id3 debra --id4 servertech --id5 techdebra --id6 servertechdebra --short "Server tech Debra" --long "Tall and lanky with a crop of untidy hair, Debra is a pretty drab-looking woman in her early twenties who probably got conned into working in this department on Core. A look of permanent boredom is etched on her face. From the way she carries herself, you gather that although her physical self is available, her mind seems to be far from Core. An air of half-heartedness hangs around her like some dark shroud." --level 8 --gender female
python core_npc.py --name "heckle" --label "Miss Heckle" --id1 miss --id2 heckle --id3 missheckle --short "Miss Heckle the North Dome librarian" --long "This dimunitive human female is the North Dome's librarian. This cheery young thing has a penchant for books, which is one of the main reasons how the Company got her to work in the North Dome's library. Here, Miss Heckle spends most of the time making idle chat with the miners who walks in and out of the place, but when no one's around, she will just whip up a book and start reading." --level 8 --gender female
python core_npc.py --name "tom" --label "Ol Tom" --id1 ol --id2 tom --id3 oltom --short "Ol Tom the miner" --long "Ol Tom is legendary. He s one of the old miners who were brought from Earth to help the Company with the mining tactics on Core. It is said that prior to his assignment on Core, Tom was one of those daredevil miners who was sent down to deal with lethal situations in the mine. Now, he's just a wrinkled old coot who just sits around reading in the North Domes reading rooms, ever waiting for the time the Company needs him again for some death-defying task." --level 12 --gender male
python core_npc.py --name "andy" --label "Andy" --id1 andy --short "Andy, Public Relations Representative" --long "Suave, slick with well-combed hair, Andy the PRO is your typical Company snake. His reputation precedes him, for you have heard a lot of bad things about him. From scandalously romancing the North Dome administrator to apple-polishing the Company Director's shoes, you get the feeling that this is one sneaky character you don't want handling your business. Theres even a serpentile look about him, as if the word snake really defines Andy." --level 10 --gender male
python core_npc.py --name "lil" --label "Lil" --id1 lil --id2 receptionist --short "Lil the North Dome Receptionist" --long "Lil is a lithe-looking nympho. Dressed in a plain-looking blouse which incidentally more than enhances her near-perfect figure, you notice that she is looking at you demurely through oval-shaped eyes. Shes the perfect nympho, put here to greet those who wish to live in this dome. For the majority of the males which work on Core, there is nothing sweeter than to be greeted by a pretty face at the end of a long day." --gender female --level 8
python core_npc.py --name "housingofficer" --label "Housing Officer" --id1 housing --id2 officer --id3 housingofficer --short "A housing officer" --long "This tired overworked housing officer looks overstressed. Dark rings are around his eyes, and he seems to be constantly nodding off at his desk. It would appear that the poor officer has been up for weeks trying to finish his workload, but there does not seem to be an end to what he is doing." --level 8 --gender male

