#!/usr/bin/env bash
python core_npc.py --name "koretech" --label "maintenance tech" --id1 maintenance --id2 tech --id3 maintenancetech --short "maintenance tech" --long "This is a rather scrawny individual who looks like he isn't quite as smart as he thinks he is. Your first clue is that he is currently using his screwdriver to scratch inside his ear. Once he notices you looking he quickly makes like he was doing something else." --level 4 --gender male
python core_npc.py --name "smallweevil" --label "small weevil" --id1 small --id2 weevil --short "small weevil" --long "A small little weevil scurries about, eating rice crumbs. Its small little feet are dragging a trail of sticky slime around." --level 10 --gender neuter
python core_npc.py --name "weevil" --label "weevil" --id1 weevil --short "Weevil" --long "This is an abnormal size weevil. It's legs have yellow and green colored claws. Slime drools from it's mouth. This particular weevil almost looks like it has some kind of brand on it's back, but it moves around too quickly for you to get a clear view.  Something is wrong about this creature. " --level 14 --gender neuter
python core_npc.py --name "angryweevil" --label "angyry weevil" --id1 angry --id2 weevil --short "Angry Weevil" --long "This weevil is large and angry!  I'd stay away, it's very aggressive right now!" --level 14 --gender neuter
python core_npc.py --name "greenslime" --label "green slime" --id1 green --id2 slime --short "Green Slime" --long "SLIME!  Or is it some kinda weevil covered in slime? You doubt anyone will ever know for sure.  This thing needs to go. It wouldn't be safe to leave it here, it could cling to you, or something worse! Only a massive amount of some kind of toxic waste or chemical could do this. The slime moves slowely toward you, making a slow sloshing noise in the slime. " --level 15 --gender neuter
python core_npc.py --name "tinyweevil" --label "tiny weevil" --id1 tiny --id2 weevil --short "Tiny Weevil" --long "A tiny little weevil scurries about, eating rice crumbs. Its small little feet are dragging a trail of sticky slime around." --level 12 --gender neuter
python core_npc.py --name "mutatedcockroach" --label "mutated cockroach" --id1 cockroach --id2 trevor --id3 mutatedcockroach --short "mutated cockroach" --long "A tiny little roach scurries about, eating rice crumbs. Its small little feet are dragging a trail of sticky slime around." --level 12 --gender neuter
python core_npc.py --name "deformedweevil" --label "deformed weevil" --id1 deformed --id2 weevil --id3 deformedweevil --short "Deformed Weevil" --long "This is an abnormaly deformed weevil. It's claws are dark black, blue, and green.  It's face has only one eye. It's skin is rough and strong, like armour.  It appears to be looking around the room  for food.  You see a brand with a name on it, 'Scrill'.  Atleast, that's all you can make of it. The legs of this deformed beast are large, making it able to travel more quickly than it's smaller kin." --gender neuter --level 16
python core_npc.py --name "culprit" --label Culprit --id1 culprit --id2 mechanic --id3 company --id4 companymechanic --short "Culprit, injured company mechanic" --long "Culprit's legs look eaten and full of slime.  He moans and complains, apologizing that he fell asleep.  It looks as if the weevils got ahold of him.  A rather large weevil, or something else.  His eyes watering, he looks up at you and tries to talk, but looks lost.  Maybe you should try asking if he needs help. " --level 16 --gender male
python core_npc.py --name "massiveweevil" --label "Massive Weevil" --id1 massive --id2 weevil --id3 massiveweevil --short "Massive Weevil" --long "This is a massive weevil, with many arms and legs. Each arm and leg is equipped with sharp talons and claws.  There are many brands that have been burnt onto its skin, but it's impossible to make them out even slightly. The skin of this weevil has extremely tough skin, like an alligator. Infact, this thing looks alot stronger than an alligator.  Something is not right about this. " --level 16 --gender neuter
