#!/bin/bash
python core_room.py --area city --name "x70y-40z0" --short "Park Entrance" --long "This park is very lush but looks to be overgrown, as if the gardening drones have abandoned this place. Vines and creepers are all over and random plants seem to be growing out of every crevice. It is also extremely humid as if somebody hacked into the climate controls." --west 1 --south 1 --north 1 --east 1 --mon1 fern --mon2 fireant
python core_room.py --area city --name "x70y-50z0" --short "EvilMog Park" --long "Random plants of all kinds seem to be haphazardly planted here, the grass is overgrown and the bugs are all over here. It looks like somebody trashed the park and then spilled a bunch of random seeds wherever they could." --north 1 --east 1 --northeast 1 --mon1 floorvine --mon2 floorvine --mon3 fieldmouse
python core_room.py --area city --name "x70y-30z0" --short "EvilMog Park" --long "The floor here is covered in some kind of alien grass and there are various plants all over the place. This park is in serious need of a weeding as invasive plant species are all over the place." --east 1 --south 1 --southeast 1 --mon1 iguana --mon2 floorvine
python core_room.py --area city --name "x80y-30z0" --short "EvilMog Park" --long "The grass here is extremely green and the trees are tall and overgrown. It is extremely humid in here as if somebody hacked the climate control system. Random plans are all over the place." --west 1 --south 1 --east 1 --mon1 snapperjaw --mon2 snapperjaw --mon3 floorvine
python core_room.py --area city --name "x80y-40z0" --short "EvilMog Park" --long "This park just seems to go on and on, almost as if its cheap filler for some sort of demonic quest thought up by overlord EvilMog. This area shows no originality and its probably just here to mess with you. A shrub is somewhere in this chaos." --item1 shrub --item1desc "Underneath this shrub is a purple button." --item2 button --item2desc "This is a giant purple button that says 'PUSH ME'" --west 1 --northwest 1 --southwest 1 --south 1 --north 1 --northeast 1 --east 1 --southeast 1 --mon1 floorvine --mon2 floorvine --mon3 snapperjaw --mon4 snapperjaw
python core_room.py --area city --name "x80y-50z0" --short "EvilMog Park" --long "Ok its blatently apparent that evilmog is running out of material, he needs coffee badly. This park extends out everywhere, grass is green, plants are overgrown, climate is humid because well it just is." --west 1 --north 1 --east 1 --mon1 zombie --mon2 snapperjaw --mon3 snapperjaw
python core_room.py --area city --name "x90y-30z0" --short "EvilMog Park" --long "This is yet more overgrown park, as if its creator doesn't really care about his own creation. Kindof how like stalingrad was a craphole this too is the dump of the game." --west 1 --south 1 --southwest 1 --mon1 zombie --mon2 snapperjaw --mon3 floorvine --mon4 floorvine
python core_room.py --area city --name "x90y-40z0" --short "EvilMog Park" --long "This really is a terrible park, its like the droids are on strike, the grass is overgrown, climate control went to hell." --west 1 --north 1 --south 1 --mon2 snapperjaw --mon3 zombie --mon1 floorvine
python core_room.py --area city --name "x90y-50z0" --short "EvilMog Park" --long "This is a rather overgrown and invasive species filled park. Grass is 2 feet tall, the trees look like a charlie brown christmas tree and it is way too humid here." --west 1 --north 1 --northwest 1 --mon1 zombie --mon2 zombie --mon3 zombie --mon4 floorvine --mon5 snapperjaw
python core_room.py --area city --name "x-20y50z0" --short "Maintenance Access Point" --long "You are at one of the fusion generator's maintenance access points. This place is where the reactor techs carry out maintenance work on the reactor like repairing and assuring that the proper reaction levels are reached. Anyone with sufficient tech skills can help maintain the generator via this access point. A button is on the wall." --west 1 --mon1 tech --mon2 tech --item1 button --item1desc "A large purple button is here, it says 'PRESS ME'"
