python core_room.py --area westmine --name "x-590y0z0" --short "West Mine - Eastern Transit Station" --long "This is it...  the crown jewel in The Company's vast mining empire.  Of all the mining facilities in all of their colonies, none can compare to the riches found within the West Mine on the Hermes-571G colony!  Here can be found the rare spaceship fueling mineral corezite -- a mineral believed only to exist in theory and impossible to reproduce in a laboratory.  Yet by some freak of creation it has ended up here!  Due to the high financial risk posed by inexperienced miners causing accidents here, only the most skilled miners may extract corezite from the West Mine." --east 17 --aeast westmasstransit --west 4 --southwest 1 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-600y-10z0" --short "Guard Barracks." --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --northeast 1 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-630y0z0" --short "West Mine - Central Transit Station" --long "This is the center of the prestigous West Mine.  The richest mine in existence in any of The Company's mining colonies, this mine specializes in the highly sought-after mineral corezite.  Any miner who frequents this mine will soon become fast friends with many a starship captain! There are some slight irregularities on the floor and walls." --east 4 --west 4 --south 4 --north 4
python core_room.py --area westmine --name "x-630y40z0" --short "West Mine - Northern Transit Station" --long "Despite the constant cleaning efforts, the maintenance crews haven't been able to completely remove the mine soot that has been ground into the floor.  This can be none other than one of The Company's mine domes." --southeast 1 --south 4 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-620y30z0" --short "Guard Barracks" --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --northwest 1 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-630y-40z0" --short "West Mine - Southern Transit Station" --long "Despite the constant cleaning efforts, the maintenance crews haven't been able to completely remove the mine soot that has been ground into the floor.  This can be none other than one of The Company's mine domes." --northwest 1 --north 4 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-640y-30z0" --short "Guard Barracks" --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --southeast 1 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-670y0z0" --short "West Mine - Western Transit Station" --long "Despite the constant cleaning efforts, the maintenance crews haven't been able to completely remove the mine soot that has been ground into the floor.  This can be none other than one of The Company's mine domes." --northeast 1 --east 4 --mon1 guard --mon2 guard
python core_room.py --area westmine --name "x-660y10z0" --short "Guard Barracks" --long "Here is where the off-duty guards take their rest.  The lighting is pleasant and subdued, and the furniture is quite comfortable.  The guards look up at you in surprise as you enter." --southwest 1 --mon1 guard --mon2 guard

