#!/bin/bash
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --name 1-a --south 1 --east 1 --up "/domains/required/rooms/start"
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-a --south 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-a --south 1 --east 1 --up "../../../domains/required/rooms/start"
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-b --west 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-c --east 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-d --1outh 1 --west 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-d --1 south 1 --west 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-d --south 1 --west 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-e --southwest 1 --south 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-f --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-g --west 1 --south 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-h --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-i --west 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 1-j --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 2-a --north 1 --southeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 2-v --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 2-b --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 2-c --north 1 --west 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 2-d --north 1 --south 1 --northeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 2-e --north 1 --south 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 2-f --west 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 2-g --north 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 2-h --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 2-i --north 1 --south 1 --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 2-j --north 1 --west 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 3-a --east 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 3-b --northwest 1 --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 3-c --north 1 --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 3-d --north 1 --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 3-e --west 1 --north 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 3-f --north 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 3-g --north 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 3-h --east 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 3-i --north 1 --west 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 3-j --north 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 4-a --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 4-b --west 1 --east 1 --south 1 --southeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 4-c --west 1 --southeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 4-d --south 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 4-e --north 1 --west 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 4-f --north 1 --southwest 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 4-g --north 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 4-h --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 4-i --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 4-j --north 1 --west 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-a --south 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-b nnorth 1 --west 1 --southeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-b north 1 --west 1 --southeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-b --north 1 --west 1 --southeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-c --northwest 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-d --northwest 1 --north 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-e northeast 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-e --northeast 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-f --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-g --southwest 1 --north 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-h --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-i --southwest 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 5-j --southwest 1 --west 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-a --north 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-a --north 1 --southeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-a --north 1 --southeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-b --east 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-c --northwest 1 --south 1 --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-d --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-e --north 1 --west 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-f --north 1 --northeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-g --north 1 --east 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-h --north 1 --west 1 --northeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name --southwest 1 --northeast 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-i --southwest 1 --northeast 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-a --north 1 --southeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-b --east 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-c --northwest 1 --west 1 --south 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-d --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-e --north 1 --west 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-f --north 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-g --north 1 --south 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-h --north 1 --west 1 --northeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-i --northeast 1 --southwest 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-j --west 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 7-a --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 7-b --northwest 1 --north 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 7-c --north 1 --southwest 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 7-d --east 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 7-e --west 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 7-f --east 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 7-g --west 1 --north 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 7-h --northeast 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 7-i --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 7-j --north 1 --west 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-a --north 1 --south 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-b --west 1 --east 1 --northeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-c --west 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-d --north 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-d --north 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-a --north 1 --south 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-b --west 1 --northeast 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-c --west 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-d --north 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-e --north 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-f --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-g --west 1 --southwest 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-h --north 1 --west 1 --southwest 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-i --southwest 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 8-j --north 1 --southwest 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 9-a --north 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 9-b --south 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 9-c --north 1 --west 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 9-d --north 1 --south 1 --southwest 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 9-e --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 9-f --west 1 --south 1 --northeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 9-g --south 1 --northeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 9-h --northeast 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 9-i --north 1 --east 1 --northeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 9-j --west 1 --south 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-a --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-b --west 1 --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-c --west 1 --northeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-d --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-e --west 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-f --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-g --west 1 --east 1 --north 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-h --west 1 --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-u --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-j --west 1 --north 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 6-f --north 1 --northeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 7-h --northeast 1 --south 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-a --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-b --west 1 --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-c --west 1 --northeast 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-d --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-f --north 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-g --north 1 --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-h --west 1 --east 1 --north 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-i --west 1 --east 1
python room_d.py --short Dungeon --dexits "The dungeon continues to the" --area dungeon --syspath '/Users/dustin.heywood1@ibm.com/git/gurba/lib/domains/dungeon/rooms/' --domain '../domain.h' --name 10-j --west 1 --north 1
