#!/usr/bin/env bash
python core_room.py --area city --short "Starport Outfitters" --long "This shop is subsidized by The Company and offers a small selection of protective clothing suitable for this colony. While not flashy by any stretch of the imagination, these clothes allow new workers to get outfitted and blend in with others on their mining shift." --name "x50y-80z0" --north 1 --mon1 abot_1_2
python core_room.py --area city --name "x-30y-40z0" --short "Armour Shop: Level 5 - 6" --long "This is yet another armour shop, I'm not going to describe the thing, you can even figure out that list will show you armor." --east 1 --mon1 abot_5_6
python core_room.py --area city --name "x-30y-50z0" --short "Armour Shop: Level 7 - 8" --long "This is yet another armour shop, EvilMog is getting lazy and not doing real full descriptions, deal with it. Type list for servics etc." --east 1 --mon1 abot_7_8
python core_room.py --area city --name "x-30y-60z0" --short "Armour Shop: Level 9 - 10" --long "This is one of the many armour shops, it specializes in armour from levels 9 to 10. Type list to get a list of armour." --east 1 --mon1 abot_9_10
python core_room.py --area city --name "x-10y-60z0" --short "Armour Shop: Level 11 - 12" --long "This is yet another armour shop, the walls are dull, the floors are dull, even the autobot is dull. Type list for a list of services." --west 1 --mon1 abot_11_12
python core_room.py --area city --name "x-30y-70z0" --short "Armour Shop: Level 13 - 14" --long "Wow this is a special armour shop, it even has decent armour or something. Type list for a list of stuff from the autobot." --east 1 --mon1 abot_13_14
python core_room.py --area city --name "x-10y-70z0" --short "Armour Shop: Level 15 - 16" --long "What a nice shop, but only sortof, it looks like all the others only maybe this area has been cleaned a bit more. It has some muchness to it. Type list for a list of services from the autobot." --west 1 --mon1 abot_15_16
python core_room.py --area city --name "x70y-70z0" --short "Company Outfitters" --long "This is yet another company armour shop, it has various items suitable for newer players. A robotic arm is ready to serve you.\n\nType '%^MAGENTA%^list%^RESET%^' to get a list of things to buy." --north 1 --mon1 abot_3_4
python core_room.py --area city --name "x-30y-80z0" --short "Armour SHop: Level 17 - 18" --long "Wow looks like they pulled out all the stops, but the same old tired autobot is here to sell you stuff. Type list for a list of services." --east 1 --mon1 abot_17_18
python core_room.py --area city --name "x-10y-80z0" --short "Armour SHop: Level 19 - 20" --long "Welcome to the flagship store, sortof, it's really all mass produced crap but its all made of super rare unobtanium mogium. Type list for a list of services." --west 1 --mon1 abot_19_20
